// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/auth (interfaces: AuthServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/auth_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/auth AuthServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/auth"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAuthServiceClient is a mock of AuthServiceClient interface.
type MockAuthServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceClientMockRecorder
	isgomock struct{}
}

// MockAuthServiceClientMockRecorder is the mock recorder for MockAuthServiceClient.
type MockAuthServiceClientMockRecorder struct {
	mock *MockAuthServiceClient
}

// NewMockAuthServiceClient creates a new mock instance.
func NewMockAuthServiceClient(ctrl *gomock.Controller) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceClient) EXPECT() *MockAuthServiceClientMockRecorder {
	return m.recorder
}

// AdminGetActivityStats mocks base method.
func (m *MockAuthServiceClient) AdminGetActivityStats(ctx context.Context, in *auth.AdminGetActivityStatsRequest, opts ...grpc.CallOption) (*auth.AdminGetActivityStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGetActivityStats", varargs...)
	ret0, _ := ret[0].(*auth.AdminGetActivityStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetActivityStats indicates an expected call of AdminGetActivityStats.
func (mr *MockAuthServiceClientMockRecorder) AdminGetActivityStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetActivityStats", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminGetActivityStats), varargs...)
}

// AdminGetStats mocks base method.
func (m *MockAuthServiceClient) AdminGetStats(ctx context.Context, in *auth.AdminGetStatsRequest, opts ...grpc.CallOption) (*auth.AdminGetStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGetStats", varargs...)
	ret0, _ := ret[0].(*auth.AdminGetStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetStats indicates an expected call of AdminGetStats.
func (mr *MockAuthServiceClientMockRecorder) AdminGetStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetStats", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminGetStats), varargs...)
}

// AdminListUsers mocks base method.
func (m *MockAuthServiceClient) AdminListUsers(ctx context.Context, in *auth.AdminListUsersRequest, opts ...grpc.CallOption) (*auth.AdminListUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminListUsers", varargs...)
	ret0, _ := ret[0].(*auth.AdminListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListUsers indicates an expected call of AdminListUsers.
func (mr *MockAuthServiceClientMockRecorder) AdminListUsers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListUsers", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminListUsers), varargs...)
}

// AdminResetPassword mocks base method.
func (m *MockAuthServiceClient) AdminResetPassword(ctx context.Context, in *auth.AdminResetPasswordRequest, opts ...grpc.CallOption) (*auth.AdminResetPasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminResetPassword", varargs...)
	ret0, _ := ret[0].(*auth.AdminResetPasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminResetPassword indicates an expected call of AdminResetPassword.
func (mr *MockAuthServiceClientMockRecorder) AdminResetPassword(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetPassword", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminResetPassword), varargs...)
}

// AdminSetBan mocks base method.
func (m *MockAuthServiceClient) AdminSetBan(ctx context.Context, in *auth.AdminSetBanRequest, opts ...grpc.CallOption) (*auth.AdminSetBanResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminSetBan", varargs...)
	ret0, _ := ret[0].(*auth.AdminSetBanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminSetBan indicates an expected call of AdminSetBan.
func (mr *MockAuthServiceClientMockRecorder) AdminSetBan(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSetBan", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminSetBan), varargs...)
}

// AdminSetPlan mocks base method.
func (m *MockAuthServiceClient) AdminSetPlan(ctx context.Context, in *auth.AdminSetPlanRequest, opts ...grpc.CallOption) (*auth.AdminSetPlanResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminSetPlan", varargs...)
	ret0, _ := ret[0].(*auth.AdminSetPlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminSetPlan indicates an expected call of AdminSetPlan.
func (mr *MockAuthServiceClientMockRecorder) AdminSetPlan(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSetPlan", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminSetPlan), varargs...)
}

// AdminUpdateUser mocks base method.
func (m *MockAuthServiceClient) AdminUpdateUser(ctx context.Context, in *auth.AdminUpdateUserRequest, opts ...grpc.CallOption) (*auth.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminUpdateUser", varargs...)
	ret0, _ := ret[0].(*auth.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUpdateUser indicates an expected call of AdminUpdateUser.
func (mr *MockAuthServiceClientMockRecorder) AdminUpdateUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateUser", reflect.TypeOf((*MockAuthServiceClient)(nil).AdminUpdateUser), varargs...)
}

// ChangeEmail mocks base method.
func (m *MockAuthServiceClient) ChangeEmail(ctx context.Context, in *auth.ChangeEmailRequest, opts ...grpc.CallOption) (*auth.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangeEmail", varargs...)
	ret0, _ := ret[0].(*auth.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockAuthServiceClientMockRecorder) ChangeEmail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).ChangeEmail), varargs...)
}

// ChangePassword mocks base method.
func (m *MockAuthServiceClient) ChangePassword(ctx context.Context, in *auth.ChangePasswordRequest, opts ...grpc.CallOption) (*auth.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	ret0, _ := ret[0].(*auth.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthServiceClientMockRecorder) ChangePassword(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthServiceClient)(nil).ChangePassword), varargs...)
}

// ConfirmEmail mocks base method.
func (m *MockAuthServiceClient) ConfirmEmail(ctx context.Context, in *auth.ConfirmEmailRequest, opts ...grpc.CallOption) (*auth.ConfirmEmailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConfirmEmail", varargs...)
	ret0, _ := ret[0].(*auth.ConfirmEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmEmail indicates an expected call of ConfirmEmail.
func (mr *MockAuthServiceClientMockRecorder) ConfirmEmail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).ConfirmEmail), varargs...)
}

// GetOAuthURL mocks base method.
func (m *MockAuthServiceClient) GetOAuthURL(ctx context.Context, in *auth.GetOAuthURLRequest, opts ...grpc.CallOption) (*auth.GetOAuthURLResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOAuthURL", varargs...)
	ret0, _ := ret[0].(*auth.GetOAuthURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthURL indicates an expected call of GetOAuthURL.
func (mr *MockAuthServiceClientMockRecorder) GetOAuthURL(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthURL", reflect.TypeOf((*MockAuthServiceClient)(nil).GetOAuthURL), varargs...)
}

// GetUserByID mocks base method.
func (m *MockAuthServiceClient) GetUserByID(ctx context.Context, in *auth.GetUserByIDRequest, opts ...grpc.CallOption) (*auth.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByID", varargs...)
	ret0, _ := ret[0].(*auth.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthServiceClientMockRecorder) GetUserByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserByID), varargs...)
}

// GetUserByIdentifier mocks base method.
func (m *MockAuthServiceClient) GetUserByIdentifier(ctx context.Context, in *auth.GetUserByIdentifierRequest, opts ...grpc.CallOption) (*auth.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByIdentifier", varargs...)
	ret0, _ := ret[0].(*auth.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByIdentifier indicates an expected call of GetUserByIdentifier.
func (mr *MockAuthServiceClientMockRecorder) GetUserByIdentifier(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByIdentifier", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserByIdentifier), varargs...)
}

// GetUserStats mocks base method.
func (m *MockAuthServiceClient) GetUserStats(ctx context.Context, in *auth.GetUserStatsRequest, opts ...grpc.CallOption) (*auth.GetUserStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserStats", varargs...)
	ret0, _ := ret[0].(*auth.GetUserStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockAuthServiceClientMockRecorder) GetUserStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserStats), varargs...)
}

// Login mocks base method.
func (m *MockAuthServiceClient) Login(ctx context.Context, in *auth.LoginRequest, opts ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceClientMockRecorder) Login(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceClient)(nil).Login), varargs...)
}

// Logout mocks base method.
func (m *MockAuthServiceClient) Logout(ctx context.Context, in *auth.LogoutRequest, opts ...grpc.CallOption) (*auth.LogoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logout", varargs...)
	ret0, _ := ret[0].(*auth.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceClientMockRecorder) Logout(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceClient)(nil).Logout), varargs...)
}

// OAuthCallback mocks base method.
func (m *MockAuthServiceClient) OAuthCallback(ctx context.Context, in *auth.OAuthCallbackRequest, opts ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OAuthCallback", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthCallback indicates an expected call of OAuthCallback.
func (mr *MockAuthServiceClientMockRecorder) OAuthCallback(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthCallback", reflect.TypeOf((*MockAuthServiceClient)(nil).OAuthCallback), varargs...)
}

// OAuthLogin mocks base method.
func (m *MockAuthServiceClient) OAuthLogin(ctx context.Context, in *auth.OAuthLoginRequest, opts ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OAuthLogin", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthLogin indicates an expected call of OAuthLogin.
func (mr *MockAuthServiceClientMockRecorder) OAuthLogin(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthLogin", reflect.TypeOf((*MockAuthServiceClient)(nil).OAuthLogin), varargs...)
}

// OAuthStart mocks base method.
func (m *MockAuthServiceClient) OAuthStart(ctx context.Context, in *auth.OAuthStartRequest, opts ...grpc.CallOption) (*auth.OAuthStartResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OAuthStart", varargs...)
	ret0, _ := ret[0].(*auth.OAuthStartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthStart indicates an expected call of OAuthStart.
func (mr *MockAuthServiceClientMockRecorder) OAuthStart(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthStart", reflect.TypeOf((*MockAuthServiceClient)(nil).OAuthStart), varargs...)
}

// Register mocks base method.
func (m *MockAuthServiceClient) Register(ctx context.Context, in *auth.RegisterRequest, opts ...grpc.CallOption) (*auth.RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*auth.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceClientMockRecorder) Register(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceClient)(nil).Register), varargs...)
}

// SetUserPlanInternal mocks base method.
func (m *MockAuthServiceClient) SetUserPlanInternal(ctx context.Context, in *auth.SetUserPlanInternalRequest, opts ...grpc.CallOption) (*auth.SetUserPlanInternalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetUserPlanInternal", varargs...)
	ret0, _ := ret[0].(*auth.SetUserPlanInternalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserPlanInternal indicates an expected call of SetUserPlanInternal.
func (mr *MockAuthServiceClientMockRecorder) SetUserPlanInternal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPlanInternal", reflect.TypeOf((*MockAuthServiceClient)(nil).SetUserPlanInternal), varargs...)
}

// TrackEvent mocks base method.
func (m *MockAuthServiceClient) TrackEvent(ctx context.Context, in *auth.TrackEventRequest, opts ...grpc.CallOption) (*auth.TrackEventResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TrackEvent", varargs...)
	ret0, _ := ret[0].(*auth.TrackEventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackEvent indicates an expected call of TrackEvent.
func (mr *MockAuthServiceClientMockRecorder) TrackEvent(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEvent", reflect.TypeOf((*MockAuthServiceClient)(nil).TrackEvent), varargs...)
}

// UpdateProfile mocks base method.
func (m *MockAuthServiceClient) UpdateProfile(ctx context.Context, in *auth.UpdateProfileRequest, opts ...grpc.CallOption) (*auth.UserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfile", varargs...)
	ret0, _ := ret[0].(*auth.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAuthServiceClientMockRecorder) UpdateProfile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAuthServiceClient)(nil).UpdateProfile), varargs...)
}

// UploadAvatar mocks base method.
func (m *MockAuthServiceClient) UploadAvatar(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[auth.UploadAvatarChunk, auth.UserResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadAvatar", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[auth.UploadAvatarChunk, auth.UserResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAuthServiceClientMockRecorder) UploadAvatar(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAuthServiceClient)(nil).UploadAvatar), varargs...)
}

// ValidateSession mocks base method.
func (m *MockAuthServiceClient) ValidateSession(ctx context.Context, in *auth.ValidateSessionRequest, opts ...grpc.CallOption) (*auth.ValidateSessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateSession", varargs...)
	ret0, _ := ret[0].(*auth.ValidateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceClientMockRecorder) ValidateSession(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthServiceClient)(nil).ValidateSession), varargs...)
}
