// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/internal/runner/container (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/container_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/internal/runner/container Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_KISS/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CleanupSessions mocks base method.
func (m *MockManager) CleanupSessions(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupSessions", ctx)
}

// CleanupSessions indicates an expected call of CleanupSessions.
func (mr *MockManagerMockRecorder) CleanupSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupSessions", reflect.TypeOf((*MockManager)(nil).CleanupSessions), ctx)
}

// Close mocks base method.
func (m *MockManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager)(nil).Close))
}

// GetContainerAddress mocks base method.
func (m *MockManager) GetContainerAddress(ctx context.Context, sessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerAddress", ctx, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerAddress indicates an expected call of GetContainerAddress.
func (mr *MockManagerMockRecorder) GetContainerAddress(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerAddress", reflect.TypeOf((*MockManager)(nil).GetContainerAddress), ctx, sessionID)
}

// GetContainerStats mocks base method.
func (m *MockManager) GetContainerStats(ctx context.Context, sessionID string) (*domain.ContainerResourceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStats", ctx, sessionID)
	ret0, _ := ret[0].(*domain.ContainerResourceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStats indicates an expected call of GetContainerStats.
func (mr *MockManagerMockRecorder) GetContainerStats(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStats", reflect.TypeOf((*MockManager)(nil).GetContainerStats), ctx, sessionID)
}

// StartSession mocks base method.
func (m *MockManager) StartSession(ctx context.Context, sessionID, language string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", ctx, sessionID, language)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSession indicates an expected call of StartSession.
func (mr *MockManagerMockRecorder) StartSession(ctx, sessionID, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockManager)(nil).StartSession), ctx, sessionID, language)
}

// StopSession mocks base method.
func (m *MockManager) StopSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockManagerMockRecorder) StopSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockManager)(nil).StopSession), ctx, sessionID)
}
