// Code generated by MockGen. DO NOT EDIT.
// Source: docker_adapter.go
//
// Generated by this command:
//
//	mockgen -source=docker_adapter.go -destination=../../../mocks/docker_adapter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	container "github.com/docker/docker/api/types/container"
	network "github.com/docker/docker/api/types/network"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockDockerAdapter is a mock of DockerAdapter interface.
type MockDockerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDockerAdapterMockRecorder
	isgomock struct{}
}

// MockDockerAdapterMockRecorder is the mock recorder for MockDockerAdapter.
type MockDockerAdapterMockRecorder struct {
	mock *MockDockerAdapter
}

// NewMockDockerAdapter creates a new mock instance.
func NewMockDockerAdapter(ctrl *gomock.Controller) *MockDockerAdapter {
	mock := &MockDockerAdapter{ctrl: ctrl}
	mock.recorder = &MockDockerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerAdapter) EXPECT() *MockDockerAdapterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDockerAdapter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDockerAdapterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDockerAdapter)(nil).Close))
}

// ContainerCreate mocks base method.
func (m *MockDockerAdapter) ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCreate", ctx, config, hostConfig, networkingConfig, platform, containerName)
	ret0, _ := ret[0].(container.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCreate indicates an expected call of ContainerCreate.
func (mr *MockDockerAdapterMockRecorder) ContainerCreate(ctx, config, hostConfig, networkingConfig, platform, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCreate", reflect.TypeOf((*MockDockerAdapter)(nil).ContainerCreate), ctx, config, hostConfig, networkingConfig, platform, containerName)
}

// ContainerInspect mocks base method.
func (m *MockDockerAdapter) ContainerInspect(ctx context.Context, containerID string) (container.InspectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerInspect", ctx, containerID)
	ret0, _ := ret[0].(container.InspectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerInspect indicates an expected call of ContainerInspect.
func (mr *MockDockerAdapterMockRecorder) ContainerInspect(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerInspect", reflect.TypeOf((*MockDockerAdapter)(nil).ContainerInspect), ctx, containerID)
}

// ContainerList mocks base method.
func (m *MockDockerAdapter) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].([]container.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockDockerAdapterMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockDockerAdapter)(nil).ContainerList), ctx, options)
}

// ContainerRemove mocks base method.
func (m *MockDockerAdapter) ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRemove", ctx, containerID, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContainerRemove indicates an expected call of ContainerRemove.
func (mr *MockDockerAdapterMockRecorder) ContainerRemove(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRemove", reflect.TypeOf((*MockDockerAdapter)(nil).ContainerRemove), ctx, containerID, options)
}

// ContainerStart mocks base method.
func (m *MockDockerAdapter) ContainerStart(ctx context.Context, containerID string, options container.StartOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStart", ctx, containerID, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContainerStart indicates an expected call of ContainerStart.
func (mr *MockDockerAdapterMockRecorder) ContainerStart(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStart", reflect.TypeOf((*MockDockerAdapter)(nil).ContainerStart), ctx, containerID, options)
}

// GetAvailableRuntimes mocks base method.
func (m *MockDockerAdapter) GetAvailableRuntimes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableRuntimes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableRuntimes indicates an expected call of GetAvailableRuntimes.
func (mr *MockDockerAdapterMockRecorder) GetAvailableRuntimes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableRuntimes", reflect.TypeOf((*MockDockerAdapter)(nil).GetAvailableRuntimes))
}
