// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/issue (interfaces: IssueServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/issue_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/issue IssueServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	issue "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/issue"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIssueServiceClient is a mock of IssueServiceClient interface.
type MockIssueServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockIssueServiceClientMockRecorder
	isgomock struct{}
}

// MockIssueServiceClientMockRecorder is the mock recorder for MockIssueServiceClient.
type MockIssueServiceClientMockRecorder struct {
	mock *MockIssueServiceClient
}

// NewMockIssueServiceClient creates a new mock instance.
func NewMockIssueServiceClient(ctrl *gomock.Controller) *MockIssueServiceClient {
	mock := &MockIssueServiceClient{ctrl: ctrl}
	mock.recorder = &MockIssueServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueServiceClient) EXPECT() *MockIssueServiceClientMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockIssueServiceClient) AddMessage(ctx context.Context, in *issue.AddIssueMessageRequest, opts ...grpc.CallOption) (*issue.AddIssueMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMessage", varargs...)
	ret0, _ := ret[0].(*issue.AddIssueMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockIssueServiceClientMockRecorder) AddMessage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockIssueServiceClient)(nil).AddMessage), varargs...)
}

// AdminGetAllIssues mocks base method.
func (m *MockIssueServiceClient) AdminGetAllIssues(ctx context.Context, in *issue.AdminGetAllIssuesRequest, opts ...grpc.CallOption) (*issue.AdminGetAllIssuesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGetAllIssues", varargs...)
	ret0, _ := ret[0].(*issue.AdminGetAllIssuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetAllIssues indicates an expected call of AdminGetAllIssues.
func (mr *MockIssueServiceClientMockRecorder) AdminGetAllIssues(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetAllIssues", reflect.TypeOf((*MockIssueServiceClient)(nil).AdminGetAllIssues), varargs...)
}

// AdminUpdateStatus mocks base method.
func (m *MockIssueServiceClient) AdminUpdateStatus(ctx context.Context, in *issue.AdminUpdateIssueStatusRequest, opts ...grpc.CallOption) (*issue.IssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminUpdateStatus", varargs...)
	ret0, _ := ret[0].(*issue.IssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUpdateStatus indicates an expected call of AdminUpdateStatus.
func (mr *MockIssueServiceClientMockRecorder) AdminUpdateStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateStatus", reflect.TypeOf((*MockIssueServiceClient)(nil).AdminUpdateStatus), varargs...)
}

// Create mocks base method.
func (m *MockIssueServiceClient) Create(ctx context.Context, in *issue.CreateIssueRequest, opts ...grpc.CallOption) (*issue.IssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*issue.IssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIssueServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockIssueServiceClient) Delete(ctx context.Context, in *issue.DeleteIssueRequest, opts ...grpc.CallOption) (*issue.DeleteIssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*issue.DeleteIssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueServiceClient)(nil).Delete), varargs...)
}

// GetAll mocks base method.
func (m *MockIssueServiceClient) GetAll(ctx context.Context, in *issue.GetAllIssuesRequest, opts ...grpc.CallOption) (*issue.GetAllIssuesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].(*issue.GetAllIssuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIssueServiceClientMockRecorder) GetAll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIssueServiceClient)(nil).GetAll), varargs...)
}

// GetByID mocks base method.
func (m *MockIssueServiceClient) GetByID(ctx context.Context, in *issue.GetIssueRequest, opts ...grpc.CallOption) (*issue.IssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(*issue.IssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIssueServiceClientMockRecorder) GetByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIssueServiceClient)(nil).GetByID), varargs...)
}

// GetStats mocks base method.
func (m *MockIssueServiceClient) GetStats(ctx context.Context, in *issue.GetIssueStatsRequest, opts ...grpc.CallOption) (*issue.IssueStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStats", varargs...)
	ret0, _ := ret[0].(*issue.IssueStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockIssueServiceClientMockRecorder) GetStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockIssueServiceClient)(nil).GetStats), varargs...)
}

// Update mocks base method.
func (m *MockIssueServiceClient) Update(ctx context.Context, in *issue.UpdateIssueRequest, opts ...grpc.CallOption) (*issue.IssueResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*issue.IssueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIssueServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueServiceClient)(nil).Update), varargs...)
}
