// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/internal/issue/repository (interfaces: IssueRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/issue_repo_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/internal/issue/repository IssueRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_KISS/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueRepository is a mock of IssueRepository interface.
type MockIssueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIssueRepositoryMockRecorder
	isgomock struct{}
}

// MockIssueRepositoryMockRecorder is the mock recorder for MockIssueRepository.
type MockIssueRepositoryMockRecorder struct {
	mock *MockIssueRepository
}

// NewMockIssueRepository creates a new mock instance.
func NewMockIssueRepository(ctrl *gomock.Controller) *MockIssueRepository {
	mock := &MockIssueRepository{ctrl: ctrl}
	mock.recorder = &MockIssueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueRepository) EXPECT() *MockIssueRepositoryMockRecorder {
	return m.recorder
}

// AdminUpdateStatus mocks base method.
func (m *MockIssueRepository) AdminUpdateStatus(ctx context.Context, id int64, status domain.IssueStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUpdateStatus indicates an expected call of AdminUpdateStatus.
func (mr *MockIssueRepositoryMockRecorder) AdminUpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateStatus", reflect.TypeOf((*MockIssueRepository)(nil).AdminUpdateStatus), ctx, id, status)
}

// Create mocks base method.
func (m *MockIssueRepository) Create(ctx context.Context, issue *domain.Issue) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, issue)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIssueRepositoryMockRecorder) Create(ctx, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueRepository)(nil).Create), ctx, issue)
}

// Delete mocks base method.
func (m *MockIssueRepository) Delete(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueRepository)(nil).Delete), ctx, id, userID)
}

// GetAll mocks base method.
func (m *MockIssueRepository) GetAll(ctx context.Context, limit, offset int, filter *domain.IssueFilter) ([]domain.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset, filter)
	ret0, _ := ret[0].([]domain.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIssueRepositoryMockRecorder) GetAll(ctx, limit, offset, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIssueRepository)(nil).GetAll), ctx, limit, offset, filter)
}

// GetByID mocks base method.
func (m *MockIssueRepository) GetByID(ctx context.Context, id int64) (*domain.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIssueRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIssueRepository)(nil).GetByID), ctx, id)
}

// GetStats mocks base method.
func (m *MockIssueRepository) GetStats(ctx context.Context) (*domain.IssueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*domain.IssueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockIssueRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockIssueRepository)(nil).GetStats), ctx)
}

// Update mocks base method.
func (m *MockIssueRepository) Update(ctx context.Context, issue *domain.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIssueRepositoryMockRecorder) Update(ctx, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueRepository)(nil).Update), ctx, issue)
}
