// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook (interfaces: NotebookServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/notebook_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook NotebookServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notebook "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNotebookServiceClient is a mock of NotebookServiceClient interface.
type MockNotebookServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotebookServiceClientMockRecorder
	isgomock struct{}
}

// MockNotebookServiceClientMockRecorder is the mock recorder for MockNotebookServiceClient.
type MockNotebookServiceClientMockRecorder struct {
	mock *MockNotebookServiceClient
}

// NewMockNotebookServiceClient creates a new mock instance.
func NewMockNotebookServiceClient(ctrl *gomock.Controller) *MockNotebookServiceClient {
	mock := &MockNotebookServiceClient{ctrl: ctrl}
	mock.recorder = &MockNotebookServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotebookServiceClient) EXPECT() *MockNotebookServiceClientMockRecorder {
	return m.recorder
}

// AddBlock mocks base method.
func (m *MockNotebookServiceClient) AddBlock(ctx context.Context, in *notebook.AddBlockRequest, opts ...grpc.CallOption) (*notebook.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBlock", varargs...)
	ret0, _ := ret[0].(*notebook.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBlock indicates an expected call of AddBlock.
func (mr *MockNotebookServiceClientMockRecorder) AddBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).AddBlock), varargs...)
}

// AdminDeleteNotebook mocks base method.
func (m *MockNotebookServiceClient) AdminDeleteNotebook(ctx context.Context, in *notebook.AdminDeleteNotebookRequest, opts ...grpc.CallOption) (*notebook.DeleteNotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminDeleteNotebook", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteNotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminDeleteNotebook indicates an expected call of AdminDeleteNotebook.
func (mr *MockNotebookServiceClientMockRecorder) AdminDeleteNotebook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteNotebook", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminDeleteNotebook), varargs...)
}

// AdminGetNotebookCount mocks base method.
func (m *MockNotebookServiceClient) AdminGetNotebookCount(ctx context.Context, in *notebook.AdminGetNotebookCountRequest, opts ...grpc.CallOption) (*notebook.AdminGetNotebookCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGetNotebookCount", varargs...)
	ret0, _ := ret[0].(*notebook.AdminGetNotebookCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetNotebookCount indicates an expected call of AdminGetNotebookCount.
func (mr *MockNotebookServiceClientMockRecorder) AdminGetNotebookCount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetNotebookCount", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminGetNotebookCount), varargs...)
}

// AdminListNotebooks mocks base method.
func (m *MockNotebookServiceClient) AdminListNotebooks(ctx context.Context, in *notebook.AdminListNotebooksRequest, opts ...grpc.CallOption) (*notebook.AdminListNotebooksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminListNotebooks", varargs...)
	ret0, _ := ret[0].(*notebook.AdminListNotebooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListNotebooks indicates an expected call of AdminListNotebooks.
func (mr *MockNotebookServiceClientMockRecorder) AdminListNotebooks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListNotebooks", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminListNotebooks), varargs...)
}

// AdminSetUserNotebooksPrivate mocks base method.
func (m *MockNotebookServiceClient) AdminSetUserNotebooksPrivate(ctx context.Context, in *notebook.AdminSetUserNotebooksPrivateRequest, opts ...grpc.CallOption) (*notebook.AdminSetUserNotebooksPrivateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminSetUserNotebooksPrivate", varargs...)
	ret0, _ := ret[0].(*notebook.AdminSetUserNotebooksPrivateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminSetUserNotebooksPrivate indicates an expected call of AdminSetUserNotebooksPrivate.
func (mr *MockNotebookServiceClientMockRecorder) AdminSetUserNotebooksPrivate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSetUserNotebooksPrivate", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminSetUserNotebooksPrivate), varargs...)
}

// Create mocks base method.
func (m *MockNotebookServiceClient) Create(ctx context.Context, in *notebook.CreateNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotebookServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotebookServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNotebookServiceClient) Delete(ctx context.Context, in *notebook.DeleteNotebookRequest, opts ...grpc.CallOption) (*notebook.DeleteNotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteNotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNotebookServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotebookServiceClient)(nil).Delete), varargs...)
}

// DeleteBlock mocks base method.
func (m *MockNotebookServiceClient) DeleteBlock(ctx context.Context, in *notebook.DeleteBlockRequest, opts ...grpc.CallOption) (*notebook.DeleteBlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBlock", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNotebookServiceClientMockRecorder) DeleteBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).DeleteBlock), varargs...)
}

// GetBlocksByNotebookID mocks base method.
func (m *MockNotebookServiceClient) GetBlocksByNotebookID(ctx context.Context, in *notebook.GetBlocksRequest, opts ...grpc.CallOption) (*notebook.GetBlocksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlocksByNotebookID", varargs...)
	ret0, _ := ret[0].(*notebook.GetBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByNotebookID indicates an expected call of GetBlocksByNotebookID.
func (mr *MockNotebookServiceClientMockRecorder) GetBlocksByNotebookID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByNotebookID", reflect.TypeOf((*MockNotebookServiceClient)(nil).GetBlocksByNotebookID), varargs...)
}

// GetByID mocks base method.
func (m *MockNotebookServiceClient) GetByID(ctx context.Context, in *notebook.GetNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotebookServiceClientMockRecorder) GetByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotebookServiceClient)(nil).GetByID), varargs...)
}

// GetUserStats mocks base method.
func (m *MockNotebookServiceClient) GetUserStats(ctx context.Context, in *notebook.GetUserNotebookStatsRequest, opts ...grpc.CallOption) (*notebook.GetUserNotebookStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserStats", varargs...)
	ret0, _ := ret[0].(*notebook.GetUserNotebookStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockNotebookServiceClientMockRecorder) GetUserStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockNotebookServiceClient)(nil).GetUserStats), varargs...)
}

// GrantPermission mocks base method.
func (m *MockNotebookServiceClient) GrantPermission(ctx context.Context, in *notebook.GrantPermissionRequest, opts ...grpc.CallOption) (*notebook.GrantPermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantPermission", varargs...)
	ret0, _ := ret[0].(*notebook.GrantPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantPermission indicates an expected call of GrantPermission.
func (mr *MockNotebookServiceClientMockRecorder) GrantPermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantPermission", reflect.TypeOf((*MockNotebookServiceClient)(nil).GrantPermission), varargs...)
}

// ImportNotebook mocks base method.
func (m *MockNotebookServiceClient) ImportNotebook(ctx context.Context, in *notebook.ImportNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ImportNotebook", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportNotebook indicates an expected call of ImportNotebook.
func (mr *MockNotebookServiceClientMockRecorder) ImportNotebook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportNotebook", reflect.TypeOf((*MockNotebookServiceClient)(nil).ImportNotebook), varargs...)
}

// ListByUser mocks base method.
func (m *MockNotebookServiceClient) ListByUser(ctx context.Context, in *notebook.ListNotebooksRequest, opts ...grpc.CallOption) (*notebook.ListNotebooksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByUser", varargs...)
	ret0, _ := ret[0].(*notebook.ListNotebooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockNotebookServiceClientMockRecorder) ListByUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListByUser), varargs...)
}

// ListPermissions mocks base method.
func (m *MockNotebookServiceClient) ListPermissions(ctx context.Context, in *notebook.ListPermissionsRequest, opts ...grpc.CallOption) (*notebook.ListPermissionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPermissions", varargs...)
	ret0, _ := ret[0].(*notebook.ListPermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockNotebookServiceClientMockRecorder) ListPermissions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListPermissions), varargs...)
}

// ListSharedWithUser mocks base method.
func (m *MockNotebookServiceClient) ListSharedWithUser(ctx context.Context, in *notebook.ListSharedWithUserRequest, opts ...grpc.CallOption) (*notebook.ListNotebooksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSharedWithUser", varargs...)
	ret0, _ := ret[0].(*notebook.ListNotebooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSharedWithUser indicates an expected call of ListSharedWithUser.
func (mr *MockNotebookServiceClientMockRecorder) ListSharedWithUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSharedWithUser", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListSharedWithUser), varargs...)
}

// ReorderBlocks mocks base method.
func (m *MockNotebookServiceClient) ReorderBlocks(ctx context.Context, in *notebook.ReorderBlocksRequest, opts ...grpc.CallOption) (*notebook.ReorderBlocksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReorderBlocks", varargs...)
	ret0, _ := ret[0].(*notebook.ReorderBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderBlocks indicates an expected call of ReorderBlocks.
func (mr *MockNotebookServiceClientMockRecorder) ReorderBlocks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderBlocks", reflect.TypeOf((*MockNotebookServiceClient)(nil).ReorderBlocks), varargs...)
}

// RevokePermission mocks base method.
func (m *MockNotebookServiceClient) RevokePermission(ctx context.Context, in *notebook.RevokePermissionRequest, opts ...grpc.CallOption) (*notebook.RevokePermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokePermission", varargs...)
	ret0, _ := ret[0].(*notebook.RevokePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokePermission indicates an expected call of RevokePermission.
func (mr *MockNotebookServiceClientMockRecorder) RevokePermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePermission", reflect.TypeOf((*MockNotebookServiceClient)(nil).RevokePermission), varargs...)
}

// SaveBlockOutputs mocks base method.
func (m *MockNotebookServiceClient) SaveBlockOutputs(ctx context.Context, in *notebook.SaveBlockOutputsRequest, opts ...grpc.CallOption) (*notebook.SaveBlockOutputsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveBlockOutputs", varargs...)
	ret0, _ := ret[0].(*notebook.SaveBlockOutputsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBlockOutputs indicates an expected call of SaveBlockOutputs.
func (mr *MockNotebookServiceClientMockRecorder) SaveBlockOutputs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBlockOutputs", reflect.TypeOf((*MockNotebookServiceClient)(nil).SaveBlockOutputs), varargs...)
}

// SubscribeNotebook mocks base method.
func (m *MockNotebookServiceClient) SubscribeNotebook(ctx context.Context, in *notebook.SubscribeNotebookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[notebook.NotebookEvent], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeNotebook", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[notebook.NotebookEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeNotebook indicates an expected call of SubscribeNotebook.
func (mr *MockNotebookServiceClientMockRecorder) SubscribeNotebook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNotebook", reflect.TypeOf((*MockNotebookServiceClient)(nil).SubscribeNotebook), varargs...)
}

// Update mocks base method.
func (m *MockNotebookServiceClient) Update(ctx context.Context, in *notebook.UpdateNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNotebookServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotebookServiceClient)(nil).Update), varargs...)
}

// UpdateBlock mocks base method.
func (m *MockNotebookServiceClient) UpdateBlock(ctx context.Context, in *notebook.UpdateBlockRequest, opts ...grpc.CallOption) (*notebook.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBlock", varargs...)
	ret0, _ := ret[0].(*notebook.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockNotebookServiceClientMockRecorder) UpdateBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).UpdateBlock), varargs...)
}

// AddComment mocks base method.
func (m *MockNotebookServiceClient) AddComment(ctx context.Context, in *notebook.AddCommentRequest, opts ...grpc.CallOption) (*notebook.AddCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddComment", varargs...)
	ret0, _ := ret[0].(*notebook.AddCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockNotebookServiceClientMockRecorder) AddComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockNotebookServiceClient)(nil).AddComment), varargs...)
}

// DeleteComment mocks base method.
func (m *MockNotebookServiceClient) DeleteComment(ctx context.Context, in *notebook.DeleteCommentRequest, opts ...grpc.CallOption) (*notebook.DeleteCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteComment", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockNotebookServiceClientMockRecorder) DeleteComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockNotebookServiceClient)(nil).DeleteComment), varargs...)
}

// ListCommentsByCell mocks base method.
func (m *MockNotebookServiceClient) ListCommentsByCell(ctx context.Context, in *notebook.ListCommentsByCellRequest, opts ...grpc.CallOption) (*notebook.ListCommentsByCellResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCommentsByCell", varargs...)
	ret0, _ := ret[0].(*notebook.ListCommentsByCellResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByCell indicates an expected call of ListCommentsByCell.
func (mr *MockNotebookServiceClientMockRecorder) ListCommentsByCell(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByCell", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListCommentsByCell), varargs...)
}

// ListCommentsByNotebook mocks base method.
func (m *MockNotebookServiceClient) ListCommentsByNotebook(ctx context.Context, in *notebook.ListCommentsByNotebookRequest, opts ...grpc.CallOption) (*notebook.ListCommentsByNotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCommentsByNotebook", varargs...)
	ret0, _ := ret[0].(*notebook.ListCommentsByNotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByNotebook indicates an expected call of ListCommentsByNotebook.
func (mr *MockNotebookServiceClientMockRecorder) ListCommentsByNotebook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByNotebook", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListCommentsByNotebook), varargs...)
}
