// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook (interfaces: NotebookServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/notebook_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook NotebookServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notebook "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebook"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNotebookServiceClient is a mock of NotebookServiceClient interface.
type MockNotebookServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotebookServiceClientMockRecorder
	isgomock struct{}
}

// MockNotebookServiceClientMockRecorder is the mock recorder for MockNotebookServiceClient.
type MockNotebookServiceClientMockRecorder struct {
	mock *MockNotebookServiceClient
}

// NewMockNotebookServiceClient creates a new mock instance.
func NewMockNotebookServiceClient(ctrl *gomock.Controller) *MockNotebookServiceClient {
	mock := &MockNotebookServiceClient{ctrl: ctrl}
	mock.recorder = &MockNotebookServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotebookServiceClient) EXPECT() *MockNotebookServiceClientMockRecorder {
	return m.recorder
}

// AddBlock mocks base method.
func (m *MockNotebookServiceClient) AddBlock(ctx context.Context, in *notebook.AddBlockRequest, opts ...grpc.CallOption) (*notebook.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBlock", varargs...)
	ret0, _ := ret[0].(*notebook.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBlock indicates an expected call of AddBlock.
func (mr *MockNotebookServiceClientMockRecorder) AddBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).AddBlock), varargs...)
}

// AdminDeleteNotebook mocks base method.
func (m *MockNotebookServiceClient) AdminDeleteNotebook(ctx context.Context, in *notebook.AdminDeleteNotebookRequest, opts ...grpc.CallOption) (*notebook.DeleteNotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminDeleteNotebook", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteNotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminDeleteNotebook indicates an expected call of AdminDeleteNotebook.
func (mr *MockNotebookServiceClientMockRecorder) AdminDeleteNotebook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteNotebook", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminDeleteNotebook), varargs...)
}

// AdminListNotebooks mocks base method.
func (m *MockNotebookServiceClient) AdminListNotebooks(ctx context.Context, in *notebook.AdminListNotebooksRequest, opts ...grpc.CallOption) (*notebook.AdminListNotebooksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminListNotebooks", varargs...)
	ret0, _ := ret[0].(*notebook.AdminListNotebooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListNotebooks indicates an expected call of AdminListNotebooks.
func (mr *MockNotebookServiceClientMockRecorder) AdminListNotebooks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListNotebooks", reflect.TypeOf((*MockNotebookServiceClient)(nil).AdminListNotebooks), varargs...)
}

// Create mocks base method.
func (m *MockNotebookServiceClient) Create(ctx context.Context, in *notebook.CreateNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNotebookServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotebookServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNotebookServiceClient) Delete(ctx context.Context, in *notebook.DeleteNotebookRequest, opts ...grpc.CallOption) (*notebook.DeleteNotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteNotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNotebookServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotebookServiceClient)(nil).Delete), varargs...)
}

// DeleteBlock mocks base method.
func (m *MockNotebookServiceClient) DeleteBlock(ctx context.Context, in *notebook.DeleteBlockRequest, opts ...grpc.CallOption) (*notebook.DeleteBlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBlock", varargs...)
	ret0, _ := ret[0].(*notebook.DeleteBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNotebookServiceClientMockRecorder) DeleteBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).DeleteBlock), varargs...)
}

// GetBlocksByNotebookID mocks base method.
func (m *MockNotebookServiceClient) GetBlocksByNotebookID(ctx context.Context, in *notebook.GetBlocksRequest, opts ...grpc.CallOption) (*notebook.GetBlocksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlocksByNotebookID", varargs...)
	ret0, _ := ret[0].(*notebook.GetBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByNotebookID indicates an expected call of GetBlocksByNotebookID.
func (mr *MockNotebookServiceClientMockRecorder) GetBlocksByNotebookID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByNotebookID", reflect.TypeOf((*MockNotebookServiceClient)(nil).GetBlocksByNotebookID), varargs...)
}

// GetByID mocks base method.
func (m *MockNotebookServiceClient) GetByID(ctx context.Context, in *notebook.GetNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotebookServiceClientMockRecorder) GetByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotebookServiceClient)(nil).GetByID), varargs...)
}

// ListByUser mocks base method.
func (m *MockNotebookServiceClient) ListByUser(ctx context.Context, in *notebook.ListNotebooksRequest, opts ...grpc.CallOption) (*notebook.ListNotebooksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByUser", varargs...)
	ret0, _ := ret[0].(*notebook.ListNotebooksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockNotebookServiceClientMockRecorder) ListByUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockNotebookServiceClient)(nil).ListByUser), varargs...)
}

// Update mocks base method.
func (m *MockNotebookServiceClient) Update(ctx context.Context, in *notebook.UpdateNotebookRequest, opts ...grpc.CallOption) (*notebook.NotebookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*notebook.NotebookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNotebookServiceClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotebookServiceClient)(nil).Update), varargs...)
}

// UpdateBlock mocks base method.
func (m *MockNotebookServiceClient) UpdateBlock(ctx context.Context, in *notebook.UpdateBlockRequest, opts ...grpc.CallOption) (*notebook.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBlock", varargs...)
	ret0, _ := ret[0].(*notebook.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockNotebookServiceClientMockRecorder) UpdateBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockNotebookServiceClient)(nil).UpdateBlock), varargs...)
}
