// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/payment (interfaces: PaymentServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/payment_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/payment PaymentServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	payment "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/payment"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentServiceClient is a mock of PaymentServiceClient interface.
type MockPaymentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentServiceClientMockRecorder is the mock recorder for MockPaymentServiceClient.
type MockPaymentServiceClientMockRecorder struct {
	mock *MockPaymentServiceClient
}

// NewMockPaymentServiceClient creates a new mock instance.
func NewMockPaymentServiceClient(ctrl *gomock.Controller) *MockPaymentServiceClient {
	mock := &MockPaymentServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceClient) EXPECT() *MockPaymentServiceClientMockRecorder {
	return m.recorder
}

// CreateSubscriptionPayment mocks base method.
func (m *MockPaymentServiceClient) CreateSubscriptionPayment(ctx context.Context, in *payment.CreateSubscriptionPaymentRequest, opts ...grpc.CallOption) (*payment.CreateSubscriptionPaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSubscriptionPayment", varargs...)
	ret0, _ := ret[0].(*payment.CreateSubscriptionPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionPayment indicates an expected call of CreateSubscriptionPayment.
func (mr *MockPaymentServiceClientMockRecorder) CreateSubscriptionPayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionPayment", reflect.TypeOf((*MockPaymentServiceClient)(nil).CreateSubscriptionPayment), varargs...)
}

// GetMySubscription mocks base method.
func (m *MockPaymentServiceClient) GetMySubscription(ctx context.Context, in *payment.GetMySubscriptionRequest, opts ...grpc.CallOption) (*payment.GetMySubscriptionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMySubscription", varargs...)
	ret0, _ := ret[0].(*payment.GetMySubscriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMySubscription indicates an expected call of GetMySubscription.
func (mr *MockPaymentServiceClientMockRecorder) GetMySubscription(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMySubscription", reflect.TypeOf((*MockPaymentServiceClient)(nil).GetMySubscription), varargs...)
}

// GetPaymentStatus mocks base method.
func (m *MockPaymentServiceClient) GetPaymentStatus(ctx context.Context, in *payment.GetPaymentStatusRequest, opts ...grpc.CallOption) (*payment.GetPaymentStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPaymentStatus", varargs...)
	ret0, _ := ret[0].(*payment.GetPaymentStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentStatus indicates an expected call of GetPaymentStatus.
func (mr *MockPaymentServiceClientMockRecorder) GetPaymentStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentStatus", reflect.TypeOf((*MockPaymentServiceClient)(nil).GetPaymentStatus), varargs...)
}

// HandleWebhook mocks base method.
func (m *MockPaymentServiceClient) HandleWebhook(ctx context.Context, in *payment.WebhookEvent, opts ...grpc.CallOption) (*payment.WebhookAck, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleWebhook", varargs...)
	ret0, _ := ret[0].(*payment.WebhookAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleWebhook indicates an expected call of HandleWebhook.
func (mr *MockPaymentServiceClientMockRecorder) HandleWebhook(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhook", reflect.TypeOf((*MockPaymentServiceClient)(nil).HandleWebhook), varargs...)
}

// ListPlans mocks base method.
func (m *MockPaymentServiceClient) ListPlans(ctx context.Context, in *payment.ListPlansRequest, opts ...grpc.CallOption) (*payment.ListPlansResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPlans", varargs...)
	ret0, _ := ret[0].(*payment.ListPlansResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockPaymentServiceClientMockRecorder) ListPlans(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockPaymentServiceClient)(nil).ListPlans), varargs...)
}
