// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/internal/runner/session_repository (interfaces: ExecutionSessionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/session_repo_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/internal/runner/session_repository ExecutionSessionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_KISS/internal/domain"
	notebook_session "github.com/go-park-mail-ru/2026_1_KISS/internal/runner/notebook_session"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionSessionRepository is a mock of ExecutionSessionRepository interface.
type MockExecutionSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutionSessionRepositoryMockRecorder is the mock recorder for MockExecutionSessionRepository.
type MockExecutionSessionRepositoryMockRecorder struct {
	mock *MockExecutionSessionRepository
}

// NewMockExecutionSessionRepository creates a new mock instance.
func NewMockExecutionSessionRepository(ctrl *gomock.Controller) *MockExecutionSessionRepository {
	mock := &MockExecutionSessionRepository{ctrl: ctrl}
	mock.recorder = &MockExecutionSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionSessionRepository) EXPECT() *MockExecutionSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockExecutionSessionRepository) CreateSession(notebook *domain.Notebook, runnerBaseURL, sessionID string) (notebook_session.NotebookSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", notebook, runnerBaseURL, sessionID)
	ret0, _ := ret[0].(notebook_session.NotebookSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockExecutionSessionRepositoryMockRecorder) CreateSession(notebook, runnerBaseURL, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockExecutionSessionRepository)(nil).CreateSession), notebook, runnerBaseURL, sessionID)
}

// DeleteSession mocks base method.
func (m *MockExecutionSessionRepository) DeleteSession(notebookID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSession", notebookID)
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockExecutionSessionRepositoryMockRecorder) DeleteSession(notebookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockExecutionSessionRepository)(nil).DeleteSession), notebookID)
}

// ListSessions mocks base method.
func (m *MockExecutionSessionRepository) ListSessions() map[int64]notebook_session.NotebookSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions")
	ret0, _ := ret[0].(map[int64]notebook_session.NotebookSession)
	return ret0
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockExecutionSessionRepositoryMockRecorder) ListSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockExecutionSessionRepository)(nil).ListSessions))
}

// GetSession mocks base method.
func (m *MockExecutionSessionRepository) GetSession(notebookID int64) (notebook_session.NotebookSession, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", notebookID)
	ret0, _ := ret[0].(notebook_session.NotebookSession)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockExecutionSessionRepositoryMockRecorder) GetSession(notebookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockExecutionSessionRepository)(nil).GetSession), notebookID)
}
