// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/pkg/api/storage (interfaces: StorageServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/storage_grpc_client_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/pkg/api/storage StorageServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/go-park-mail-ru/2026_1_KISS/pkg/api/storage"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockStorageServiceClient is a mock of StorageServiceClient interface.
type MockStorageServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceClientMockRecorder
	isgomock struct{}
}

// MockStorageServiceClientMockRecorder is the mock recorder for MockStorageServiceClient.
type MockStorageServiceClientMockRecorder struct {
	mock *MockStorageServiceClient
}

// NewMockStorageServiceClient creates a new mock instance.
func NewMockStorageServiceClient(ctrl *gomock.Controller) *MockStorageServiceClient {
	mock := &MockStorageServiceClient{ctrl: ctrl}
	mock.recorder = &MockStorageServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageServiceClient) EXPECT() *MockStorageServiceClientMockRecorder {
	return m.recorder
}

// AdminListFiles mocks base method.
func (m *MockStorageServiceClient) AdminListFiles(ctx context.Context, in *storage.AdminListFilesRequest, opts ...grpc.CallOption) (*storage.ListFilesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminListFiles", varargs...)
	ret0, _ := ret[0].(*storage.ListFilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListFiles indicates an expected call of AdminListFiles.
func (mr *MockStorageServiceClientMockRecorder) AdminListFiles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListFiles", reflect.TypeOf((*MockStorageServiceClient)(nil).AdminListFiles), varargs...)
}

// DeleteFile mocks base method.
func (m *MockStorageServiceClient) DeleteFile(ctx context.Context, in *storage.DeleteFileRequest, opts ...grpc.CallOption) (*storage.DeleteFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFile", varargs...)
	ret0, _ := ret[0].(*storage.DeleteFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockStorageServiceClientMockRecorder) DeleteFile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockStorageServiceClient)(nil).DeleteFile), varargs...)
}

// DeleteFileByURL mocks base method.
func (m *MockStorageServiceClient) DeleteFileByURL(ctx context.Context, in *storage.DeleteFileByURLRequest, opts ...grpc.CallOption) (*storage.DeleteFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFileByURL", varargs...)
	ret0, _ := ret[0].(*storage.DeleteFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFileByURL indicates an expected call of DeleteFileByURL.
func (mr *MockStorageServiceClientMockRecorder) DeleteFileByURL(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileByURL", reflect.TypeOf((*MockStorageServiceClient)(nil).DeleteFileByURL), varargs...)
}

// GetFile mocks base method.
func (m *MockStorageServiceClient) GetFile(ctx context.Context, in *storage.GetFileRequest, opts ...grpc.CallOption) (*storage.FileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFile", varargs...)
	ret0, _ := ret[0].(*storage.FileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockStorageServiceClientMockRecorder) GetFile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockStorageServiceClient)(nil).GetFile), varargs...)
}

// GetStorageStats mocks base method.
func (m *MockStorageServiceClient) GetStorageStats(ctx context.Context, in *storage.GetStorageStatsRequest, opts ...grpc.CallOption) (*storage.GetStorageStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStorageStats", varargs...)
	ret0, _ := ret[0].(*storage.GetStorageStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageStats indicates an expected call of GetStorageStats.
func (mr *MockStorageServiceClientMockRecorder) GetStorageStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageStats", reflect.TypeOf((*MockStorageServiceClient)(nil).GetStorageStats), varargs...)
}

// GetUserStorageStats mocks base method.
func (m *MockStorageServiceClient) GetUserStorageStats(ctx context.Context, in *storage.GetUserStorageStatsRequest, opts ...grpc.CallOption) (*storage.GetStorageStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserStorageStats", varargs...)
	ret0, _ := ret[0].(*storage.GetStorageStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStorageStats indicates an expected call of GetUserStorageStats.
func (mr *MockStorageServiceClientMockRecorder) GetUserStorageStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStorageStats", reflect.TypeOf((*MockStorageServiceClient)(nil).GetUserStorageStats), varargs...)
}

// ListFiles mocks base method.
func (m *MockStorageServiceClient) ListFiles(ctx context.Context, in *storage.ListFilesRequest, opts ...grpc.CallOption) (*storage.ListFilesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFiles", varargs...)
	ret0, _ := ret[0].(*storage.ListFilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockStorageServiceClientMockRecorder) ListFiles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockStorageServiceClient)(nil).ListFiles), varargs...)
}

// UploadFile mocks base method.
func (m *MockStorageServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[storage.UploadFileChunk, storage.FileResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadFile", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[storage.UploadFileChunk, storage.FileResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockStorageServiceClientMockRecorder) UploadFile(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockStorageServiceClient)(nil).UploadFile), varargs...)
}
