// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_KISS/internal/runner/runner_service (interfaces: WorkerPool)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/worker_pool_mock.go -package=mocks github.com/go-park-mail-ru/2026_1_KISS/internal/runner/runner_service WorkerPool
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_KISS/internal/domain"
	pool "github.com/go-park-mail-ru/2026_1_KISS/internal/runner/pool"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkerPool is a mock of WorkerPool interface.
type MockWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolMockRecorder
	isgomock struct{}
}

// MockWorkerPoolMockRecorder is the mock recorder for MockWorkerPool.
type MockWorkerPoolMockRecorder struct {
	mock *MockWorkerPool
}

// NewMockWorkerPool creates a new mock instance.
func NewMockWorkerPool(ctrl *gomock.Controller) *MockWorkerPool {
	mock := &MockWorkerPool{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPool) EXPECT() *MockWorkerPoolMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockWorkerPool) Acquire(ctx context.Context, notebookID, userID int64) (*pool.Worker, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, notebookID, userID)
	ret0, _ := ret[0].(*pool.Worker)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockWorkerPoolMockRecorder) Acquire(ctx, notebookID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockWorkerPool)(nil).Acquire), ctx, notebookID, userID)
}

// GetContainerStats mocks base method.
func (m *MockWorkerPool) GetContainerStats(ctx context.Context, workerID string) (*domain.ContainerResourceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStats", ctx, workerID)
	ret0, _ := ret[0].(*domain.ContainerResourceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStats indicates an expected call of GetContainerStats.
func (mr *MockWorkerPoolMockRecorder) GetContainerStats(ctx, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStats", reflect.TypeOf((*MockWorkerPool)(nil).GetContainerStats), ctx, workerID)
}

// QueuePositionFor mocks base method.
func (m *MockWorkerPool) QueuePositionFor(notebookID int64) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueuePositionFor", notebookID)
	ret0, _ := ret[0].(int32)
	return ret0
}

// QueuePositionFor indicates an expected call of QueuePositionFor.
func (mr *MockWorkerPoolMockRecorder) QueuePositionFor(notebookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueuePositionFor", reflect.TypeOf((*MockWorkerPool)(nil).QueuePositionFor), notebookID)
}

// Release mocks base method.
func (m *MockWorkerPool) Release(ctx context.Context, w *pool.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release", ctx, w)
}

// Release indicates an expected call of Release.
func (mr *MockWorkerPoolMockRecorder) Release(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockWorkerPool)(nil).Release), ctx, w)
}

// Shutdown mocks base method.
func (m *MockWorkerPool) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockWorkerPoolMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockWorkerPool)(nil).Shutdown), ctx)
}
