// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/notebook/notebook.proto

package notebook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotebookInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Blocks        []*BlockInfo           `protobuf:"bytes,5,rep,name=blocks,proto3" json:"blocks,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotebookInfo) Reset() {
	*x = NotebookInfo{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotebookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookInfo) ProtoMessage() {}

func (x *NotebookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookInfo.ProtoReflect.Descriptor instead.
func (*NotebookInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{0}
}

func (x *NotebookInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotebookInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *NotebookInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotebookInfo) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *NotebookInfo) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *NotebookInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NotebookInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type BlockInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NotebookId     int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Position       int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExecutionCount *int32                 `protobuf:"varint,9,opt,name=execution_count,json=executionCount,proto3,oneof" json:"execution_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{1}
}

func (x *BlockInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlockInfo) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *BlockInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlockInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BlockInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlockInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *BlockInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BlockInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *BlockInfo) GetExecutionCount() int32 {
	if x != nil && x.ExecutionCount != nil {
		return *x.ExecutionCount
	}
	return 0
}

type CreateNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotebookRequest) Reset() {
	*x = CreateNotebookRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotebookRequest) ProtoMessage() {}

func (x *CreateNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotebookRequest.ProtoReflect.Descriptor instead.
func (*CreateNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotebookRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNotebookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotebookRequest) Reset() {
	*x = GetNotebookRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookRequest) ProtoMessage() {}

func (x *GetNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookRequest.ProtoReflect.Descriptor instead.
func (*GetNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotebookRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNotebookRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

type ListNotebooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotebooksRequest) Reset() {
	*x = ListNotebooksRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotebooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotebooksRequest) ProtoMessage() {}

func (x *ListNotebooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotebooksRequest.ProtoReflect.Descriptor instead.
func (*ListNotebooksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{4}
}

func (x *ListNotebooksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListNotebooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotebooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListNotebooksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type UpdateNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsPublic      bool                   `protobuf:"varint,4,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotebookRequest) Reset() {
	*x = UpdateNotebookRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotebookRequest) ProtoMessage() {}

func (x *UpdateNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotebookRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNotebookRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNotebookRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *UpdateNotebookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNotebookRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type DeleteNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotebookRequest) Reset() {
	*x = DeleteNotebookRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotebookRequest) ProtoMessage() {}

func (x *DeleteNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotebookRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotebookRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteNotebookRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

type AddBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlockRequest) Reset() {
	*x = AddBlockRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlockRequest) ProtoMessage() {}

func (x *AddBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlockRequest.ProtoReflect.Descriptor instead.
func (*AddBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{7}
}

func (x *AddBlockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddBlockRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *AddBlockRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddBlockRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AddBlockRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	BlockId       int64                  `protobuf:"varint,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockRequest) Reset() {
	*x = UpdateBlockRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockRequest) ProtoMessage() {}

func (x *UpdateBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBlockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBlockRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *UpdateBlockRequest) GetBlockId() int64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *UpdateBlockRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateBlockRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateBlockRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type DeleteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotebookId    int64                  `protobuf:"varint,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	BlockId       int64                  `protobuf:"varint,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockRequest) Reset() {
	*x = DeleteBlockRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockRequest) ProtoMessage() {}

func (x *DeleteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBlockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteBlockRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *DeleteBlockRequest) GetBlockId() int64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    int64                  `protobuf:"varint,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlocksRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *GetBlocksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NotebookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notebook      *NotebookInfo          `protobuf:"bytes,1,opt,name=notebook,proto3" json:"notebook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotebookResponse) Reset() {
	*x = NotebookResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookResponse) ProtoMessage() {}

func (x *NotebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookResponse.ProtoReflect.Descriptor instead.
func (*NotebookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{11}
}

func (x *NotebookResponse) GetNotebook() *NotebookInfo {
	if x != nil {
		return x.Notebook
	}
	return nil
}

type ListNotebooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notebooks     []*NotebookInfo        `protobuf:"bytes,1,rep,name=notebooks,proto3" json:"notebooks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotebooksResponse) Reset() {
	*x = ListNotebooksResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotebooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotebooksResponse) ProtoMessage() {}

func (x *ListNotebooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotebooksResponse.ProtoReflect.Descriptor instead.
func (*ListNotebooksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{12}
}

func (x *ListNotebooksResponse) GetNotebooks() []*NotebookInfo {
	if x != nil {
		return x.Notebooks
	}
	return nil
}

func (x *ListNotebooksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotebooksResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotebooksResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockInfo             `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{13}
}

func (x *BlockResponse) GetBlock() *BlockInfo {
	if x != nil {
		return x.Block
	}
	return nil
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockInfo           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{14}
}

func (x *GetBlocksResponse) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type DeleteNotebookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotebookResponse) Reset() {
	*x = DeleteNotebookResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotebookResponse) ProtoMessage() {}

func (x *DeleteNotebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotebookResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotebookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{15}
}

type DeleteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockResponse) Reset() {
	*x = DeleteBlockResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockResponse) ProtoMessage() {}

func (x *DeleteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{16}
}

type AdminListNotebooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListNotebooksRequest) Reset() {
	*x = AdminListNotebooksRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListNotebooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListNotebooksRequest) ProtoMessage() {}

func (x *AdminListNotebooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListNotebooksRequest.ProtoReflect.Descriptor instead.
func (*AdminListNotebooksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{17}
}

func (x *AdminListNotebooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminListNotebooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AdminListNotebooksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type AdminListNotebooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notebooks     []*NotebookInfo        `protobuf:"bytes,1,rep,name=notebooks,proto3" json:"notebooks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListNotebooksResponse) Reset() {
	*x = AdminListNotebooksResponse{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListNotebooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListNotebooksResponse) ProtoMessage() {}

func (x *AdminListNotebooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListNotebooksResponse.ProtoReflect.Descriptor instead.
func (*AdminListNotebooksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{18}
}

func (x *AdminListNotebooksResponse) GetNotebooks() []*NotebookInfo {
	if x != nil {
		return x.Notebooks
	}
	return nil
}

func (x *AdminListNotebooksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AdminDeleteNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    int64                  `protobuf:"varint,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteNotebookRequest) Reset() {
	*x = AdminDeleteNotebookRequest{}
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteNotebookRequest) ProtoMessage() {}

func (x *AdminDeleteNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notebook_notebook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteNotebookRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notebook_notebook_proto_rawDescGZIP(), []int{19}
}

func (x *AdminDeleteNotebookRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

var File_api_proto_notebook_notebook_proto protoreflect.FileDescriptor

const file_api_proto_notebook_notebook_proto_rawDesc = "" +
	"\n" +
	"!api/proto/notebook/notebook.proto\x12\bnotebook\"\xd7\x01\n" +
	"\fNotebookInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\x12+\n" +
	"\x06blocks\x18\x05 \x03(\v2\x13.notebook.BlockInfoR\x06blocks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa2\x02\n" +
	"\tBlockInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12,\n" +
	"\x0fexecution_count\x18\t \x01(\x05H\x00R\x0eexecutionCount\x88\x01\x01B\x12\n" +
	"\x10_execution_count\"F\n" +
	"\x15CreateNotebookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"N\n" +
	"\x12GetNotebookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\"u\n" +
	"\x14ListNotebooksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\x84\x01\n" +
	"\x15UpdateNotebookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tis_public\x18\x04 \x01(\bR\bisPublic\"Q\n" +
	"\x15DeleteNotebookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\"\x95\x01\n" +
	"\x0fAddBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"\xb3\x01\n" +
	"\x12UpdateBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\x12\x19\n" +
	"\bblock_id\x18\x03 \x01(\x03R\ablockId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"i\n" +
	"\x12DeleteBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\x03R\n" +
	"notebookId\x12\x19\n" +
	"\bblock_id\x18\x03 \x01(\x03R\ablockId\"L\n" +
	"\x10GetBlocksRequest\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\x03R\n" +
	"notebookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"F\n" +
	"\x10NotebookResponse\x122\n" +
	"\bnotebook\x18\x01 \x01(\v2\x16.notebook.NotebookInfoR\bnotebook\"\x91\x01\n" +
	"\x15ListNotebooksResponse\x124\n" +
	"\tnotebooks\x18\x01 \x03(\v2\x16.notebook.NotebookInfoR\tnotebooks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\":\n" +
	"\rBlockResponse\x12)\n" +
	"\x05block\x18\x01 \x01(\v2\x13.notebook.BlockInfoR\x05block\"@\n" +
	"\x11GetBlocksResponse\x12+\n" +
	"\x06blocks\x18\x01 \x03(\v2\x13.notebook.BlockInfoR\x06blocks\"\x18\n" +
	"\x16DeleteNotebookResponse\"\x15\n" +
	"\x13DeleteBlockResponse\"a\n" +
	"\x19AdminListNotebooksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"h\n" +
	"\x1aAdminListNotebooksResponse\x124\n" +
	"\tnotebooks\x18\x01 \x03(\v2\x16.notebook.NotebookInfoR\tnotebooks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"=\n" +
	"\x1aAdminDeleteNotebookRequest\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\x03R\n" +
	"notebookId2\xe4\x06\n" +
	"\x0fNotebookService\x12E\n" +
	"\x06Create\x12\x1f.notebook.CreateNotebookRequest\x1a\x1a.notebook.NotebookResponse\x12C\n" +
	"\aGetByID\x12\x1c.notebook.GetNotebookRequest\x1a\x1a.notebook.NotebookResponse\x12M\n" +
	"\n" +
	"ListByUser\x12\x1e.notebook.ListNotebooksRequest\x1a\x1f.notebook.ListNotebooksResponse\x12E\n" +
	"\x06Update\x12\x1f.notebook.UpdateNotebookRequest\x1a\x1a.notebook.NotebookResponse\x12K\n" +
	"\x06Delete\x12\x1f.notebook.DeleteNotebookRequest\x1a .notebook.DeleteNotebookResponse\x12>\n" +
	"\bAddBlock\x12\x19.notebook.AddBlockRequest\x1a\x17.notebook.BlockResponse\x12D\n" +
	"\vUpdateBlock\x12\x1c.notebook.UpdateBlockRequest\x1a\x17.notebook.BlockResponse\x12J\n" +
	"\vDeleteBlock\x12\x1c.notebook.DeleteBlockRequest\x1a\x1d.notebook.DeleteBlockResponse\x12P\n" +
	"\x15GetBlocksByNotebookID\x12\x1a.notebook.GetBlocksRequest\x1a\x1b.notebook.GetBlocksResponse\x12_\n" +
	"\x12AdminListNotebooks\x12#.notebook.AdminListNotebooksRequest\x1a$.notebook.AdminListNotebooksResponse\x12]\n" +
	"\x13AdminDeleteNotebook\x12$.notebook.AdminDeleteNotebookRequest\x1a .notebook.DeleteNotebookResponseB9Z7github.com/go-park-mail-ru/2026_1_KISS/pkg/api/notebookb\x06proto3"

var (
	file_api_proto_notebook_notebook_proto_rawDescOnce sync.Once
	file_api_proto_notebook_notebook_proto_rawDescData []byte
)

func file_api_proto_notebook_notebook_proto_rawDescGZIP() []byte {
	file_api_proto_notebook_notebook_proto_rawDescOnce.Do(func() {
		file_api_proto_notebook_notebook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notebook_notebook_proto_rawDesc), len(file_api_proto_notebook_notebook_proto_rawDesc)))
	})
	return file_api_proto_notebook_notebook_proto_rawDescData
}

var file_api_proto_notebook_notebook_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_notebook_notebook_proto_goTypes = []any{
	(*NotebookInfo)(nil),               // 0: notebook.NotebookInfo
	(*BlockInfo)(nil),                  // 1: notebook.BlockInfo
	(*CreateNotebookRequest)(nil),      // 2: notebook.CreateNotebookRequest
	(*GetNotebookRequest)(nil),         // 3: notebook.GetNotebookRequest
	(*ListNotebooksRequest)(nil),       // 4: notebook.ListNotebooksRequest
	(*UpdateNotebookRequest)(nil),      // 5: notebook.UpdateNotebookRequest
	(*DeleteNotebookRequest)(nil),      // 6: notebook.DeleteNotebookRequest
	(*AddBlockRequest)(nil),            // 7: notebook.AddBlockRequest
	(*UpdateBlockRequest)(nil),         // 8: notebook.UpdateBlockRequest
	(*DeleteBlockRequest)(nil),         // 9: notebook.DeleteBlockRequest
	(*GetBlocksRequest)(nil),           // 10: notebook.GetBlocksRequest
	(*NotebookResponse)(nil),           // 11: notebook.NotebookResponse
	(*ListNotebooksResponse)(nil),      // 12: notebook.ListNotebooksResponse
	(*BlockResponse)(nil),              // 13: notebook.BlockResponse
	(*GetBlocksResponse)(nil),          // 14: notebook.GetBlocksResponse
	(*DeleteNotebookResponse)(nil),     // 15: notebook.DeleteNotebookResponse
	(*DeleteBlockResponse)(nil),        // 16: notebook.DeleteBlockResponse
	(*AdminListNotebooksRequest)(nil),  // 17: notebook.AdminListNotebooksRequest
	(*AdminListNotebooksResponse)(nil), // 18: notebook.AdminListNotebooksResponse
	(*AdminDeleteNotebookRequest)(nil), // 19: notebook.AdminDeleteNotebookRequest
}
var file_api_proto_notebook_notebook_proto_depIdxs = []int32{
	1,  // 0: notebook.NotebookInfo.blocks:type_name -> notebook.BlockInfo
	0,  // 1: notebook.NotebookResponse.notebook:type_name -> notebook.NotebookInfo
	0,  // 2: notebook.ListNotebooksResponse.notebooks:type_name -> notebook.NotebookInfo
	1,  // 3: notebook.BlockResponse.block:type_name -> notebook.BlockInfo
	1,  // 4: notebook.GetBlocksResponse.blocks:type_name -> notebook.BlockInfo
	0,  // 5: notebook.AdminListNotebooksResponse.notebooks:type_name -> notebook.NotebookInfo
	2,  // 6: notebook.NotebookService.Create:input_type -> notebook.CreateNotebookRequest
	3,  // 7: notebook.NotebookService.GetByID:input_type -> notebook.GetNotebookRequest
	4,  // 8: notebook.NotebookService.ListByUser:input_type -> notebook.ListNotebooksRequest
	5,  // 9: notebook.NotebookService.Update:input_type -> notebook.UpdateNotebookRequest
	6,  // 10: notebook.NotebookService.Delete:input_type -> notebook.DeleteNotebookRequest
	7,  // 11: notebook.NotebookService.AddBlock:input_type -> notebook.AddBlockRequest
	8,  // 12: notebook.NotebookService.UpdateBlock:input_type -> notebook.UpdateBlockRequest
	9,  // 13: notebook.NotebookService.DeleteBlock:input_type -> notebook.DeleteBlockRequest
	10, // 14: notebook.NotebookService.GetBlocksByNotebookID:input_type -> notebook.GetBlocksRequest
	17, // 15: notebook.NotebookService.AdminListNotebooks:input_type -> notebook.AdminListNotebooksRequest
	19, // 16: notebook.NotebookService.AdminDeleteNotebook:input_type -> notebook.AdminDeleteNotebookRequest
	11, // 17: notebook.NotebookService.Create:output_type -> notebook.NotebookResponse
	11, // 18: notebook.NotebookService.GetByID:output_type -> notebook.NotebookResponse
	12, // 19: notebook.NotebookService.ListByUser:output_type -> notebook.ListNotebooksResponse
	11, // 20: notebook.NotebookService.Update:output_type -> notebook.NotebookResponse
	15, // 21: notebook.NotebookService.Delete:output_type -> notebook.DeleteNotebookResponse
	13, // 22: notebook.NotebookService.AddBlock:output_type -> notebook.BlockResponse
	13, // 23: notebook.NotebookService.UpdateBlock:output_type -> notebook.BlockResponse
	16, // 24: notebook.NotebookService.DeleteBlock:output_type -> notebook.DeleteBlockResponse
	14, // 25: notebook.NotebookService.GetBlocksByNotebookID:output_type -> notebook.GetBlocksResponse
	18, // 26: notebook.NotebookService.AdminListNotebooks:output_type -> notebook.AdminListNotebooksResponse
	15, // 27: notebook.NotebookService.AdminDeleteNotebook:output_type -> notebook.DeleteNotebookResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_notebook_notebook_proto_init() }
func file_api_proto_notebook_notebook_proto_init() {
	if File_api_proto_notebook_notebook_proto != nil {
		return
	}
	file_api_proto_notebook_notebook_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notebook_notebook_proto_rawDesc), len(file_api_proto_notebook_notebook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notebook_notebook_proto_goTypes,
		DependencyIndexes: file_api_proto_notebook_notebook_proto_depIdxs,
		MessageInfos:      file_api_proto_notebook_notebook_proto_msgTypes,
	}.Build()
	File_api_proto_notebook_notebook_proto = out.File
	file_api_proto_notebook_notebook_proto_goTypes = nil
	file_api_proto_notebook_notebook_proto_depIdxs = nil
}
