// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package notebook_session

import (
	json "encoding/json"
	domain "github.com/go-park-mail-ru/2026_1_KISS/internal/domain"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(in *jlexer.Lexer, out *streamChunk) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "mime_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MimeType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(out *jwriter.Writer, in streamChunk) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	if in.MimeType != "" {
		const prefix string = ",\"mime_type\":"
		out.RawString(prefix)
		out.String(string(in.MimeType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v streamChunk) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v streamChunk) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *streamChunk) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *streamChunk) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession(l, v)
}
func easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(in *jlexer.Lexer, out *notebookSession) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "NotebookID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotebookID = int64(in.Int64())
			}
		case "SessionID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SessionID = string(in.String())
			}
		case "BaseURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BaseURL = string(in.String())
			}
		case "LastExecuted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastExecuted = int(in.Int())
			}
		case "BlockStates":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.BlockStates = make(map[int64]*domain.BlockState)
				for !in.IsDelim('}') {
					key := int64(in.Int64Str())
					in.WantColon()
					var v1 *domain.BlockState
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(domain.BlockState)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v1).UnmarshalEasyJSON(in)
						}
					}
					(out.BlockStates)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(out *jwriter.Writer, in notebookSession) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NotebookID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.NotebookID))
	}
	{
		const prefix string = ",\"SessionID\":"
		out.RawString(prefix)
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"BaseURL\":"
		out.RawString(prefix)
		out.String(string(in.BaseURL))
	}
	{
		const prefix string = ",\"LastExecuted\":"
		out.RawString(prefix)
		out.Int(int(in.LastExecuted))
	}
	{
		const prefix string = ",\"BlockStates\":"
		out.RawString(prefix)
		if in.BlockStates == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.BlockStates {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.Int64Str(int64(v2Name))
				out.RawByte(':')
				if v2Value == nil {
					out.RawString("null")
				} else {
					(*v2Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v notebookSession) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v notebookSession) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f25a18aEncodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *notebookSession) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *notebookSession) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f25a18aDecodeGithubComGoParkMailRu20261KISSInternalRunnerNotebookSession1(l, v)
}
