apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: PBFA97CFB590B2093

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB:-colab}
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: false
    editable: false
    uid: POSTGRESQL_DS_001
