// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *registerRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in registerRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v registerRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v registerRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *registerRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *registerRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *loginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in loginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v loginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v loginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *loginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *loginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *AuthHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in AuthHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD9f9b93bEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD9f9b93bDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
