// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *fileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "owner_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerID = int64(in.Int64())
			}
		case "notebook_id":
			if in.IsNull() {
				in.Skip()
				out.NotebookID = nil
			} else {
				if out.NotebookID == nil {
					out.NotebookID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NotebookID = int64(in.Int64())
				}
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "filename":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Filename = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "mime_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MIMEType = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in fileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.OwnerID))
	}
	if in.NotebookID != nil {
		const prefix string = ",\"notebook_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.NotebookID))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"filename\":"
		out.RawString(prefix)
		out.String(string(in.Filename))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"mime_type\":"
		out.RawString(prefix)
		out.String(string(in.MIMEType))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v fileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v fileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *fileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *fileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *fileListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "files":
			if in.IsNull() {
				in.Skip()
				out.Files = nil
			} else {
				in.Delim('[')
				if out.Files == nil {
					if !in.IsDelim(']') {
						out.Files = make([]fileResponse, 0, 0)
					} else {
						out.Files = []fileResponse{}
					}
				} else {
					out.Files = (out.Files)[:0]
				}
				for !in.IsDelim(']') {
					var v1 fileResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Files = append(out.Files, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int32(in.Int32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in fileListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"files\":"
		out.RawString(prefix[1:])
		if in.Files == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Files {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int32(int32(in.Total))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v fileListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v fileListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *fileListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *fileListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *FileHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in FileHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF44d1953EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF44d1953DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
