// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *patchIssueStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in patchIssueStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v patchIssueStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v patchIssueStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *patchIssueStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *patchIssueStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *issueStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int64(in.Int64())
			}
		case "open":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Open = int64(in.Int64())
			}
		case "in_progress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InProgress = int64(in.Int64())
			}
		case "closed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Closed = int64(in.Int64())
			}
		case "by_category":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.ByCategory).UnmarshalEasyJSON(in)
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in issueStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Total))
	}
	{
		const prefix string = ",\"open\":"
		out.RawString(prefix)
		out.Int64(int64(in.Open))
	}
	{
		const prefix string = ",\"in_progress\":"
		out.RawString(prefix)
		out.Int64(int64(in.InProgress))
	}
	{
		const prefix string = ",\"closed\":"
		out.RawString(prefix)
		out.Int64(int64(in.Closed))
	}
	{
		const prefix string = ",\"by_category\":"
		out.RawString(prefix)
		(in.ByCategory).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issueStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issueStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issueStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issueStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *issueResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]issueMessageResponse, 0, 0)
					} else {
						out.Messages = []issueMessageResponse{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v1 issueMessageResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in issueResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Messages {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issueResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issueResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issueResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issueResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(in *jlexer.Lexer, out *issueMessageResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "issue_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IssueID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "is_admin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAdmin = bool(in.Bool())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(out *jwriter.Writer, in issueMessageResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"issue_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.IssueID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	if in.Username != "" {
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"is_admin\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsAdmin))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issueMessageResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issueMessageResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issueMessageResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issueMessageResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(in *jlexer.Lexer, out *issueListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "issues":
			if in.IsNull() {
				in.Skip()
				out.Issues = nil
			} else {
				in.Delim('[')
				if out.Issues == nil {
					if !in.IsDelim(']') {
						out.Issues = make([]issueResponse, 0, 0)
					} else {
						out.Issues = []issueResponse{}
					}
				} else {
					out.Issues = (out.Issues)[:0]
				}
				for !in.IsDelim(']') {
					var v4 issueResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Issues = append(out.Issues, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(out *jwriter.Writer, in issueListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"issues\":"
		out.RawString(prefix[1:])
		if in.Issues == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Issues {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issueListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issueListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issueListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issueListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(in *jlexer.Lexer, out *issueCategoryStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bug":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Bug = int64(in.Int64())
			}
		case "idea":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Idea = int64(in.Int64())
			}
		case "problem":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Problem = int64(in.Int64())
			}
		case "feedback":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Feedback = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(out *jwriter.Writer, in issueCategoryStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bug\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Bug))
	}
	{
		const prefix string = ",\"idea\":"
		out.RawString(prefix)
		out.Int64(int64(in.Idea))
	}
	{
		const prefix string = ",\"problem\":"
		out.RawString(prefix)
		out.Int64(int64(in.Problem))
	}
	{
		const prefix string = ",\"feedback\":"
		out.RawString(prefix)
		out.Int64(int64(in.Feedback))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issueCategoryStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issueCategoryStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issueCategoryStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issueCategoryStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(in *jlexer.Lexer, out *createIssueRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(out *jwriter.Writer, in createIssueRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createIssueRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createIssueRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createIssueRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createIssueRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(in *jlexer.Lexer, out *adminIssueResponseRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(out *jwriter.Writer, in adminIssueResponseRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v adminIssueResponseRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v adminIssueResponseRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *adminIssueResponseRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *adminIssueResponseRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(in *jlexer.Lexer, out *adminIssueResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]issueMessageResponse, 0, 0)
					} else {
						out.Messages = []issueMessageResponse{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v7 issueMessageResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(out *jwriter.Writer, in adminIssueResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	if in.Username != "" {
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Messages {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v adminIssueResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v adminIssueResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *adminIssueResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *adminIssueResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(in *jlexer.Lexer, out *adminIssueListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "issues":
			if in.IsNull() {
				in.Skip()
				out.Issues = nil
			} else {
				in.Delim('[')
				if out.Issues == nil {
					if !in.IsDelim(']') {
						out.Issues = make([]adminIssueResponse, 0, 0)
					} else {
						out.Issues = []adminIssueResponse{}
					}
				} else {
					out.Issues = (out.Issues)[:0]
				}
				for !in.IsDelim(']') {
					var v10 adminIssueResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Issues = append(out.Issues, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(out *jwriter.Writer, in adminIssueListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"issues\":"
		out.RawString(prefix[1:])
		if in.Issues == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Issues {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v adminIssueListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v adminIssueListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *adminIssueListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *adminIssueListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(in *jlexer.Lexer, out *addMessageRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(out *jwriter.Writer, in addMessageRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v addMessageRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v addMessageRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *addMessageRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *addMessageRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(l, v)
}
func easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(in *jlexer.Lexer, out *IssueHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(out *jwriter.Writer, in IssueHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IssueHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IssueHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE1f7a9f6EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IssueHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IssueHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE1f7a9f6DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(l, v)
}
