// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *updateNotebookRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "is_public":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsPublic = bool(in.Bool())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in updateNotebookRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"is_public\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v updateNotebookRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v updateNotebookRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *updateNotebookRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *updateNotebookRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *updateBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in updateBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v updateBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v updateBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *updateBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *updateBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *reorderBlocksRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "block_ids":
			if in.IsNull() {
				in.Skip()
				out.BlockIDs = nil
			} else {
				in.Delim('[')
				if out.BlockIDs == nil {
					if !in.IsDelim(']') {
						out.BlockIDs = make([]int64, 0, 8)
					} else {
						out.BlockIDs = []int64{}
					}
				} else {
					out.BlockIDs = (out.BlockIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					out.BlockIDs = append(out.BlockIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in reorderBlocksRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_ids\":"
		out.RawString(prefix[1:])
		if in.BlockIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.BlockIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v reorderBlocksRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v reorderBlocksRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *reorderBlocksRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *reorderBlocksRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(in *jlexer.Lexer, out *permissionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "notebook_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotebookID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "permission_level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PermissionLevel = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(out *jwriter.Writer, in permissionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"notebook_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.NotebookID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"permission_level\":"
		out.RawString(prefix)
		out.String(string(in.PermissionLevel))
	}
	if in.Email != "" {
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v permissionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v permissionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *permissionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *permissionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(in *jlexer.Lexer, out *permissionListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "permissions":
			if in.IsNull() {
				in.Skip()
				out.Permissions = nil
			} else {
				in.Delim('[')
				if out.Permissions == nil {
					if !in.IsDelim(']') {
						out.Permissions = make([]permissionResponse, 0, 1)
					} else {
						out.Permissions = []permissionResponse{}
					}
				} else {
					out.Permissions = (out.Permissions)[:0]
				}
				for !in.IsDelim(']') {
					var v4 permissionResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Permissions = append(out.Permissions, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(out *jwriter.Writer, in permissionListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"permissions\":"
		out.RawString(prefix[1:])
		if in.Permissions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Permissions {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v permissionListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v permissionListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *permissionListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *permissionListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(in *jlexer.Lexer, out *notebookResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "owner_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerID = int64(in.Int64())
			}
		case "owner_username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerUsername = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "is_public":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsPublic = bool(in.Bool())
			}
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]blockResponse, 0, 0)
					} else {
						out.Blocks = []blockResponse{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v7 blockResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Blocks = append(out.Blocks, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "your_permission":
			if in.IsNull() {
				in.Skip()
			} else {
				out.YourPermission = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(out *jwriter.Writer, in notebookResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"owner_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.OwnerID))
	}
	if in.OwnerUsername != "" {
		const prefix string = ",\"owner_username\":"
		out.RawString(prefix)
		out.String(string(in.OwnerUsername))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"is_public\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	if len(in.Blocks) != 0 {
		const prefix string = ",\"blocks\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.Blocks {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	if in.YourPermission != "" {
		const prefix string = ",\"your_permission\":"
		out.RawString(prefix)
		out.String(string(in.YourPermission))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v notebookResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v notebookResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *notebookResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *notebookResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(in *jlexer.Lexer, out *notebookListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "notebooks":
			if in.IsNull() {
				in.Skip()
				out.Notebooks = nil
			} else {
				in.Delim('[')
				if out.Notebooks == nil {
					if !in.IsDelim(']') {
						out.Notebooks = make([]notebookResponse, 0, 0)
					} else {
						out.Notebooks = []notebookResponse{}
					}
				} else {
					out.Notebooks = (out.Notebooks)[:0]
				}
				for !in.IsDelim(']') {
					var v10 notebookResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Notebooks = append(out.Notebooks, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(out *jwriter.Writer, in notebookListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"notebooks\":"
		out.RawString(prefix[1:])
		if in.Notebooks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Notebooks {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v notebookListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v notebookListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *notebookListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *notebookListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(in *jlexer.Lexer, out *importNotebookRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]importBlockRequest, 0, 0)
					} else {
						out.Blocks = []importBlockRequest{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v13 importBlockRequest
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Blocks = append(out.Blocks, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(out *jwriter.Writer, in importNotebookRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix)
		if in.Blocks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Blocks {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v importNotebookRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v importNotebookRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *importNotebookRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *importNotebookRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(in *jlexer.Lexer, out *importBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int(in.Int())
			}
		case "outputs":
			if in.IsNull() {
				in.Skip()
				out.Outputs = nil
			} else {
				in.Delim('[')
				if out.Outputs == nil {
					if !in.IsDelim(']') {
						out.Outputs = make([]importBlockOutput, 0, 1)
					} else {
						out.Outputs = []importBlockOutput{}
					}
				} else {
					out.Outputs = (out.Outputs)[:0]
				}
				for !in.IsDelim(']') {
					var v16 importBlockOutput
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Outputs = append(out.Outputs, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(out *jwriter.Writer, in importBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	if len(in.Outputs) != 0 {
		const prefix string = ",\"outputs\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v17, v18 := range in.Outputs {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v importBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v importBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *importBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *importBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler8(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(in *jlexer.Lexer, out *importBlockOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "output_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputType = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int(in.Int())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(out *jwriter.Writer, in importBlockOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"output_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.OutputType))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v importBlockOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v importBlockOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *importBlockOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *importBlockOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler9(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(in *jlexer.Lexer, out *grantPermissionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(out *jwriter.Writer, in grantPermissionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix[1:])
		out.String(string(in.Level))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v grantPermissionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v grantPermissionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *grantPermissionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *grantPermissionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler10(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(in *jlexer.Lexer, out *grantPermissionByIdentifierRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "identifier":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Identifier = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(out *jwriter.Writer, in grantPermissionByIdentifierRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"identifier\":"
		out.RawString(prefix[1:])
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.String(string(in.Level))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v grantPermissionByIdentifierRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v grantPermissionByIdentifierRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *grantPermissionByIdentifierRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *grantPermissionByIdentifierRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler11(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(in *jlexer.Lexer, out *createNotebookRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(out *jwriter.Writer, in createNotebookRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createNotebookRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createNotebookRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createNotebookRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createNotebookRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler12(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(in *jlexer.Lexer, out *createBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(out *jwriter.Writer, in createBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler13(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(in *jlexer.Lexer, out *commentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "block_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockID = int64(in.Int64())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(out *jwriter.Writer, in commentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"block_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockID))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v commentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v commentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *commentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *commentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler14(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(in *jlexer.Lexer, out *blockResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int(in.Int())
			}
		case "outputs":
			if in.IsNull() {
				in.Skip()
				out.Outputs = nil
			} else {
				in.Delim('[')
				if out.Outputs == nil {
					if !in.IsDelim(']') {
						out.Outputs = make([]blockOutputResponse, 0, 1)
					} else {
						out.Outputs = []blockOutputResponse{}
					}
				} else {
					out.Outputs = (out.Outputs)[:0]
				}
				for !in.IsDelim(']') {
					var v19 blockOutputResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.Outputs = append(out.Outputs, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(out *jwriter.Writer, in blockResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	if len(in.Outputs) != 0 {
		const prefix string = ",\"outputs\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v20, v21 := range in.Outputs {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v blockResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v blockResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *blockResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *blockResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler15(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(in *jlexer.Lexer, out *blockOutputResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "output_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputType = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int(in.Int())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(out *jwriter.Writer, in blockOutputResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"output_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.OutputType))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v blockOutputResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v blockOutputResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *blockOutputResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *blockOutputResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler16(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(in *jlexer.Lexer, out *addCommentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(out *jwriter.Writer, in addCommentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v addCommentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v addCommentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *addCommentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *addCommentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler17(l, v)
}
func easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(in *jlexer.Lexer, out *NotebookHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(out *jwriter.Writer, in NotebookHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NotebookHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotebookHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson203f7daEncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NotebookHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotebookHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson203f7daDecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler18(l, v)
}
