// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *storageStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "total_files":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalFiles = int64(in.Int64())
			}
		case "total_size_bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalSizeBytes = int64(in.Int64())
			}
		case "files_by_category":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.FilesByCategory = make(map[string]int64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					(out.FilesByCategory)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "size_by_category":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SizeByCategory = make(map[string]int64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int64(in.Int64())
					}
					(out.SizeByCategory)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in storageStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"total_files\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TotalFiles))
	}
	{
		const prefix string = ",\"total_size_bytes\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalSizeBytes))
	}
	{
		const prefix string = ",\"files_by_category\":"
		out.RawString(prefix)
		if in.FilesByCategory == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.FilesByCategory {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				out.Int64(int64(v3Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"size_by_category\":"
		out.RawString(prefix)
		if in.SizeByCategory == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.SizeByCategory {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.Int64(int64(v4Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v storageStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v storageStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *storageStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *storageStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *statsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "quota":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Quota).UnmarshalEasyJSON(in)
			}
		case "activity":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Activity).UnmarshalEasyJSON(in)
			}
		case "resources":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Resources).UnmarshalEasyJSON(in)
			}
		case "storage":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Storage).UnmarshalEasyJSON(in)
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in statsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"quota\":"
		out.RawString(prefix[1:])
		(in.Quota).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"activity\":"
		out.RawString(prefix)
		(in.Activity).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"resources\":"
		out.RawString(prefix)
		(in.Resources).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"storage\":"
		out.RawString(prefix)
		(in.Storage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v statsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v statsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *statsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *statsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *resourceStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "notebook_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotebookCount = int64(in.Int64())
			}
		case "block_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockCount = int64(in.Int64())
			}
		case "total_executions":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalExecutions = int64(in.Int64())
			}
		case "daily_executions":
			if in.IsNull() {
				in.Skip()
				out.DailyExecutions = nil
			} else {
				in.Delim('[')
				if out.DailyExecutions == nil {
					if !in.IsDelim(']') {
						out.DailyExecutions = make([]execItem, 0, 2)
					} else {
						out.DailyExecutions = []execItem{}
					}
				} else {
					out.DailyExecutions = (out.DailyExecutions)[:0]
				}
				for !in.IsDelim(']') {
					var v5 execItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.DailyExecutions = append(out.DailyExecutions, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in resourceStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"notebook_count\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.NotebookCount))
	}
	{
		const prefix string = ",\"block_count\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockCount))
	}
	{
		const prefix string = ",\"total_executions\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalExecutions))
	}
	{
		const prefix string = ",\"daily_executions\":"
		out.RawString(prefix)
		if in.DailyExecutions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.DailyExecutions {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v resourceStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v resourceStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *resourceStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *resourceStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(in *jlexer.Lexer, out *quotaStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "plan":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Plan = string(in.String())
			}
		case "total_time_seconds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalTimeSeconds = int64(in.Int64())
			}
		case "time_limit_seconds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TimeLimitSeconds = int64(in.Int64())
			}
		case "usage_percent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UsagePercent = float64(in.Float64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(out *jwriter.Writer, in quotaStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"plan\":"
		out.RawString(prefix[1:])
		out.String(string(in.Plan))
	}
	{
		const prefix string = ",\"total_time_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalTimeSeconds))
	}
	{
		const prefix string = ",\"time_limit_seconds\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeLimitSeconds))
	}
	{
		const prefix string = ",\"usage_percent\":"
		out.RawString(prefix)
		out.Float64(float64(in.UsagePercent))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v quotaStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v quotaStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *quotaStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *quotaStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(in *jlexer.Lexer, out *execItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(out *jwriter.Writer, in execItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int64(int64(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v execItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v execItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *execItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *execItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(in *jlexer.Lexer, out *dauItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(out *jwriter.Writer, in dauItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int64(int64(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v dauItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v dauItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *dauItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *dauItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler5(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(in *jlexer.Lexer, out *activityStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "last_active_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastActiveAt = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "daily_activity":
			if in.IsNull() {
				in.Skip()
				out.DailyActivity = nil
			} else {
				in.Delim('[')
				if out.DailyActivity == nil {
					if !in.IsDelim(']') {
						out.DailyActivity = make([]dauItem, 0, 2)
					} else {
						out.DailyActivity = []dauItem{}
					}
				} else {
					out.DailyActivity = (out.DailyActivity)[:0]
				}
				for !in.IsDelim(']') {
					var v8 dauItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v8).UnmarshalEasyJSON(in)
					}
					out.DailyActivity = append(out.DailyActivity, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(out *jwriter.Writer, in activityStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_active_at\":"
		out.RawString(prefix[1:])
		out.String(string(in.LastActiveAt))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"daily_activity\":"
		out.RawString(prefix)
		if in.DailyActivity == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.DailyActivity {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v activityStats) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v activityStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *activityStats) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *activityStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler6(l, v)
}
func easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(in *jlexer.Lexer, out *StatsHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(out *jwriter.Writer, in StatsHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBaab8c82EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBaab8c82DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler7(l, v)
}
