// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(in *jlexer.Lexer, out *wsOutgoing) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "block":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Block).UnmarshalJSON(data))
				}
			}
		case "block_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockID = int64(in.Int64())
			}
		case "actor_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ActorID = int64(in.Int64())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(out *jwriter.Writer, in wsOutgoing) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if len(in.Block) != 0 {
		const prefix string = ",\"block\":"
		out.RawString(prefix)
		out.Raw((in.Block).MarshalJSON())
	}
	if in.BlockID != 0 {
		const prefix string = ",\"block_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockID))
	}
	if in.ActorID != 0 {
		const prefix string = ",\"actor_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ActorID))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsOutgoing) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsOutgoing) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsOutgoing) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsOutgoing) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler(l, v)
}
func easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(in *jlexer.Lexer, out *wsIncoming) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "block_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockID = int64(in.Int64())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "block_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockType = string(in.String())
			}
		case "block_position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockPosition = int32(in.Int32())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(out *jwriter.Writer, in wsIncoming) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.BlockID != 0 {
		const prefix string = ",\"block_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockID))
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	if in.Language != "" {
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	if in.BlockType != "" {
		const prefix string = ",\"block_type\":"
		out.RawString(prefix)
		out.String(string(in.BlockType))
	}
	if in.BlockPosition != 0 {
		const prefix string = ",\"block_position\":"
		out.RawString(prefix)
		out.Int32(int32(in.BlockPosition))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsIncoming) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsIncoming) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsIncoming) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsIncoming) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler1(l, v)
}
func easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(in *jlexer.Lexer, out *wsExecuteResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "block_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockID = int64(in.Int64())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int32(in.Int32())
			}
		case "stdout":
			if in.IsNull() {
				in.Skip()
				out.Stdout = nil
			} else {
				in.Delim('[')
				if out.Stdout == nil {
					if !in.IsDelim(']') {
						out.Stdout = make([]string, 0, 4)
					} else {
						out.Stdout = []string{}
					}
				} else {
					out.Stdout = (out.Stdout)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Stdout = append(out.Stdout, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stderr":
			if in.IsNull() {
				in.Skip()
				out.Stderr = nil
			} else {
				in.Delim('[')
				if out.Stderr == nil {
					if !in.IsDelim(']') {
						out.Stderr = make([]string, 0, 4)
					} else {
						out.Stderr = []string{}
					}
				} else {
					out.Stderr = (out.Stderr)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.Stderr = append(out.Stderr, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Result = string(in.String())
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		case "executed_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExecutedAt = int64(in.Int64())
			}
		case "duration_ns":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationNs = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(out *jwriter.Writer, in wsExecuteResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.BlockID))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int32(int32(in.Position))
	}
	{
		const prefix string = ",\"stdout\":"
		out.RawString(prefix)
		if in.Stdout == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Stdout {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"stderr\":"
		out.RawString(prefix)
		if in.Stderr == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Stderr {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		out.String(string(in.Result))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"executed_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.ExecutedAt))
	}
	{
		const prefix string = ",\"duration_ns\":"
		out.RawString(prefix)
		out.Int64(int64(in.DurationNs))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsExecuteResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsExecuteResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsExecuteResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsExecuteResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler2(l, v)
}
func easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(in *jlexer.Lexer, out *wsBlock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "notebook_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotebookID = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "language":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Language = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Position = int32(in.Int32())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = int64(in.Int64())
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = int64(in.Int64())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(out *jwriter.Writer, in wsBlock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"notebook_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.NotebookID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int32(int32(in.Position))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreatedAt))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsBlock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsBlock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsBlock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsBlock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler3(l, v)
}
func easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(in *jlexer.Lexer, out *WSHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(out *jwriter.Writer, in WSHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WSHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WSHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFefaa3f3EncodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WSHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WSHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFefaa3f3DecodeGithubComGoParkMailRu20261KISSInternalGatewayHandler4(l, v)
}
