global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: auth
    static_configs:
      - targets: ["auth:9090"]

  - job_name: notebook
    static_configs:
      - targets: ["notebook:9090"]

  - job_name: runner
    static_configs:
      - targets: ["runner:9090"]

  - job_name: storage
    static_configs:
      - targets: ["storage:9090"]

  - job_name: issue
    static_configs:
      - targets: ["issue:9090"]

  - job_name: notification
    static_configs:
      - targets: ["notification:9090"]

  - job_name: payment
    static_configs:
      - targets: ["payment:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]