// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/runner/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteFromPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    int64                  `protobuf:"varint,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	BlockPosition int32                  `protobuf:"varint,2,opt,name=block_position,json=blockPosition,proto3" json:"block_position,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFromPositionRequest) Reset() {
	*x = ExecuteFromPositionRequest{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFromPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFromPositionRequest) ProtoMessage() {}

func (x *ExecuteFromPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFromPositionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFromPositionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteFromPositionRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *ExecuteFromPositionRequest) GetBlockPosition() int32 {
	if x != nil {
		return x.BlockPosition
	}
	return 0
}

func (x *ExecuteFromPositionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExecuteFromPositionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*BlockExecutionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteFromPositionResponse) Reset() {
	*x = ExecuteFromPositionResponse{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteFromPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFromPositionResponse) ProtoMessage() {}

func (x *ExecuteFromPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFromPositionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFromPositionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteFromPositionResponse) GetResults() []*BlockExecutionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExecuteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    int64                  `protobuf:"varint,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	BlockPosition int32                  `protobuf:"varint,2,opt,name=block_position,json=blockPosition,proto3" json:"block_position,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockRequest) Reset() {
	*x = ExecuteBlockRequest{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockRequest) ProtoMessage() {}

func (x *ExecuteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteBlockRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *ExecuteBlockRequest) GetBlockPosition() int32 {
	if x != nil {
		return x.BlockPosition
	}
	return 0
}

func (x *ExecuteBlockRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExecuteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BlockExecutionResult  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockResponse) Reset() {
	*x = ExecuteBlockResponse{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockResponse) ProtoMessage() {}

func (x *ExecuteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteBlockResponse) GetResult() *BlockExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    int64                  `protobuf:"varint,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{4}
}

func (x *StopSessionRequest) GetNotebookId() int64 {
	if x != nil {
		return x.NotebookId
	}
	return 0
}

func (x *StopSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{5}
}

type BlockExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       int64                  `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Stdout        []string               `protobuf:"bytes,3,rep,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []string               `protobuf:"bytes,4,rep,name=stderr,proto3" json:"stderr,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedAt    int64                  `protobuf:"varint,7,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	DurationNs    int64                  `protobuf:"varint,8,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockExecutionResult) Reset() {
	*x = BlockExecutionResult{}
	mi := &file_api_proto_runner_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockExecutionResult) ProtoMessage() {}

func (x *BlockExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runner_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockExecutionResult.ProtoReflect.Descriptor instead.
func (*BlockExecutionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_runner_runner_proto_rawDescGZIP(), []int{6}
}

func (x *BlockExecutionResult) GetBlockId() int64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockExecutionResult) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *BlockExecutionResult) GetStdout() []string {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *BlockExecutionResult) GetStderr() []string {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *BlockExecutionResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *BlockExecutionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BlockExecutionResult) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

func (x *BlockExecutionResult) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

var File_api_proto_runner_runner_proto protoreflect.FileDescriptor

const file_api_proto_runner_runner_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/runner/runner.proto\x12\x06runner\"}\n" +
	"\x1aExecuteFromPositionRequest\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\x03R\n" +
	"notebookId\x12%\n" +
	"\x0eblock_position\x18\x02 \x01(\x05R\rblockPosition\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"U\n" +
	"\x1bExecuteFromPositionResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.runner.BlockExecutionResultR\aresults\"v\n" +
	"\x13ExecuteBlockRequest\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\x03R\n" +
	"notebookId\x12%\n" +
	"\x0eblock_position\x18\x02 \x01(\x05R\rblockPosition\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"L\n" +
	"\x14ExecuteBlockResponse\x124\n" +
	"\x06result\x18\x01 \x01(\v2\x1c.runner.BlockExecutionResultR\x06result\"N\n" +
	"\x12StopSessionRequest\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\x03R\n" +
	"notebookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x15\n" +
	"\x13StopSessionResponse\"\xed\x01\n" +
	"\x14BlockExecutionResult\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x03R\ablockId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x16\n" +
	"\x06stdout\x18\x03 \x03(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x03(\tR\x06stderr\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vexecuted_at\x18\a \x01(\x03R\n" +
	"executedAt\x12\x1f\n" +
	"\vduration_ns\x18\b \x01(\x03R\n" +
	"durationNs2\x82\x02\n" +
	"\rRunnerService\x12^\n" +
	"\x13ExecuteFromPosition\x12\".runner.ExecuteFromPositionRequest\x1a#.runner.ExecuteFromPositionResponse\x12I\n" +
	"\fExecuteBlock\x12\x1b.runner.ExecuteBlockRequest\x1a\x1c.runner.ExecuteBlockResponse\x12F\n" +
	"\vStopSession\x12\x1a.runner.StopSessionRequest\x1a\x1b.runner.StopSessionResponseB7Z5github.com/go-park-mail-ru/2026_1_KISS/pkg/api/runnerb\x06proto3"

var (
	file_api_proto_runner_runner_proto_rawDescOnce sync.Once
	file_api_proto_runner_runner_proto_rawDescData []byte
)

func file_api_proto_runner_runner_proto_rawDescGZIP() []byte {
	file_api_proto_runner_runner_proto_rawDescOnce.Do(func() {
		file_api_proto_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_runner_runner_proto_rawDesc), len(file_api_proto_runner_runner_proto_rawDesc)))
	})
	return file_api_proto_runner_runner_proto_rawDescData
}

var file_api_proto_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_runner_runner_proto_goTypes = []any{
	(*ExecuteFromPositionRequest)(nil),  // 0: runner.ExecuteFromPositionRequest
	(*ExecuteFromPositionResponse)(nil), // 1: runner.ExecuteFromPositionResponse
	(*ExecuteBlockRequest)(nil),         // 2: runner.ExecuteBlockRequest
	(*ExecuteBlockResponse)(nil),        // 3: runner.ExecuteBlockResponse
	(*StopSessionRequest)(nil),          // 4: runner.StopSessionRequest
	(*StopSessionResponse)(nil),         // 5: runner.StopSessionResponse
	(*BlockExecutionResult)(nil),        // 6: runner.BlockExecutionResult
}
var file_api_proto_runner_runner_proto_depIdxs = []int32{
	6, // 0: runner.ExecuteFromPositionResponse.results:type_name -> runner.BlockExecutionResult
	6, // 1: runner.ExecuteBlockResponse.result:type_name -> runner.BlockExecutionResult
	0, // 2: runner.RunnerService.ExecuteFromPosition:input_type -> runner.ExecuteFromPositionRequest
	2, // 3: runner.RunnerService.ExecuteBlock:input_type -> runner.ExecuteBlockRequest
	4, // 4: runner.RunnerService.StopSession:input_type -> runner.StopSessionRequest
	1, // 5: runner.RunnerService.ExecuteFromPosition:output_type -> runner.ExecuteFromPositionResponse
	3, // 6: runner.RunnerService.ExecuteBlock:output_type -> runner.ExecuteBlockResponse
	5, // 7: runner.RunnerService.StopSession:output_type -> runner.StopSessionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_runner_runner_proto_init() }
func file_api_proto_runner_runner_proto_init() {
	if File_api_proto_runner_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_runner_runner_proto_rawDesc), len(file_api_proto_runner_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_runner_runner_proto_goTypes,
		DependencyIndexes: file_api_proto_runner_runner_proto_depIdxs,
		MessageInfos:      file_api_proto_runner_runner_proto_msgTypes,
	}.Build()
	File_api_proto_runner_runner_proto = out.File
	file_api_proto_runner_runner_proto_goTypes = nil
	file_api_proto_runner_runner_proto_depIdxs = nil
}
