// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httputil

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7a1b8754DecodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(in *jlexer.Lexer, out *errorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7a1b8754EncodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(out *jwriter.Writer, in errorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Error != "" {
		const prefix string = ",\"error\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v errorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7a1b8754EncodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v errorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7a1b8754EncodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *errorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7a1b8754DecodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *errorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7a1b8754DecodeGithubComGoParkMailRu20261KISSInternalPkgHttputil(l, v)
}
